### ISSUE TITLE
Disconnecting on Startup

### ISSUE THREAD

**Issue by arb** [s-a/iron-node#100]
Every time I try to use Iron Node, I am greeting this error message. 

> DevTools was disconnected from the page. Once page is reloaded, DevTools will automatically reconnect.

![image](https://cloud.githubusercontent.com/assets/1591483/14434737/7873900a-ffe2-11e5-89cd-a0b40cc4c9e3.png)

iron-node has been working fine for me for over a month and just recently started doing this. After I close the dialog, iron-node doesn't do anything and I can not use any of the debugging tools. It's like a hard crash without any errors.

**Comment by s-a** [comment]
What version and OS are you using?

**Comment by arb** [comment]
iron-node 2.2.16. Using OSX 10.10.5

**Comment by s-a** [comment]
Since it stopped to work for you you might have changed something on your machine? Installed electron global? Using nvm? Or changed iron-node configuration? 
Does this error show when you start `$ iron-node;` without parameters?

You could try 2.2.17 which contains a never electron build.

**Comment by arb** [comment]
No to global electron. I did maybe change my electron config when I was trying to get a C++ module working, but I'm not sure exactly what I did. How can I reset my iron-node config? The error does show up briefly when running just `iron-node;`

**Comment by s-a** [comment]
I mean to remember that users reported iron-node loads global installed electron instead of local installed. I think you can check a global insalled electron with `npm list -g electron;` If so i would try do uninstall the global electron version.  

You can simply reset iron-node when you delete global an local config file called .iron-node.js described at https://github.com/s-a/iron-node/blob/master/docs/CONFIGURATION.md

**Comment by arb** [comment]
I do not have electron globally installed. 

I'm on OSX and never bothered to set up a global config file, where is it located on disk? I looked where global node modules are installed and could not find a folder named AppData.

**Comment by s-a** [comment]
@arb iron-node got an own tag at stackoverflow. You will get a lot more attention there. Unfortunately I have no Mac to support you more. 😞

**Comment by arb** [comment]
Ok. Thanks for the heads up.
