### ISSUE TITLE
Error running iron-node with babe-node and mocha on windows

### ISSUE THREAD

**Issue by kumarr88** [s-a/iron-node#102]
Hey,
 I tried running iron-node for debugging when running unit tests. This is how my package.json looks
{
'test-no-coverage': 'iron-node babel-node ./node_modules/mocha/bin/_mocha unit_tests/*_/_.js --compilers js:babel-core/register --require /unit_tests/setup.js'
}

when running npm run test-no-coverage , the chrome opens up with message "dev tools was disconnected on startup" 

when i see the node console 

[2244:0421/102245:ERROR:CONSOLE(7117)] "File system error: A requested file or d
irectory could not be found at the time an operation was processed. when request
ing entry '/node_modules/istanbul/node_modules/istanbul-api/node_modules/istanbu
l-reports/node_modules/handlebars/node_modules/uglify-js/node_modules/yargs/node
_modules/cliui/node_modules/right-align/node_modules/align-text/node_modules/rep
eat-string'", source: chrome-devtools://devtools/bundled/inspector.js (7117)
[2244:0421/102245:ERROR:CONSOLE(7117)] "File system error: A requested file or d
irectory could not be found at the time an operation was processed. when request
ing entry '/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/no
de_modules/anymatch/node_modules/micromatch/node_modules/braces/node_modules/exp
and-range/node_modules/fill-range/node_modules/isobject/node_modules/isarray/bui
ld'", source: chrome-devtools://devtools/bundled/inspector.js (7117)

i get more errors similar to this..

i have installed iron-node as global .. Let me know if more information is needed.

**Comment by s-a** [comment]
`babel-node` seems to be a global shell command. An iron-node debug session need a JavaScript file as start parameter.
