### ISSUE TITLE
debugger is not being hit on OSX

### ISSUE THREAD

**Issue by Qix-** [s-a/iron-node#106]
Currently can't use IronNode due to breakpoints being cleared upon reload on OS X (cmd-R).

![breakpointscleared](https://cloud.githubusercontent.com/assets/885648/15381674/74db9bc4-1d36-11e6-8f73-b59a4df20fce.gif)

Is this a known bug? Is there a workaround?

Also, why in the world does it not honor `debugger;` statements?

**Comment by s-a** [comment]
You have the filesystem version in  view. You cannot set breakpoints there. while a Debugger statement should always work. But be shure you are viewing the in memory version of you JavaScript by double check the code is surounded by the node module wrapper code to set breakpoints.
If the Debugger does not trigger : Is it possible the code will never be reached?

**Comment by Qix-** [comment]
Setting a breakpoint in the memory version didn't work, either. Why can't I set breakpoints in the files? That makes no sense.

The debugger statement was being hit - that was the main script being called. The command was literally

``` console
$ iron-node ./test.js
```

`node-debug` worked just fine. That's what I had to use.

**Comment by s-a** [comment]
Cannot reproduce this behavior on windows 10 ironNode 3.0.4. Setting breakpoints works and debugger breaks code execution without problems.

**Comment by Qix-** [comment]
Alright, that's on Windows 10. Obviously this is an OS X specific bug... `node-debug` works just fine.

**Comment by Qix-** [comment]
That also doesn't explain why `debugger;` didn't work.

**Comment by euge** [comment]
Same here...debugger is not being hit on OSX

**Comment by s-a** [comment]
pls try the latest release of electron. Will publish a version in a few seconds

**Comment by dtothefp** [comment]
think I'm having the same issue, sorry if I filed a duplicate https://github.com/s-a/iron-node/issues/108. iron-node v2.2.15

**Comment by s-a** [comment]
Unfortunately I do not work with Mac anymore. So I can not support this issue directly. 
Can you try to upgrade electron to latest version in ironNode 3.x?

https://github.com/s-a/iron-node/blob/master/docs/CHANGE-ELECTRON-VERSION.md

Otherwise we need to create an issue at the electron repo.

**Comment by babsonmatt** [comment]
electron-prebuilt 1.2.2 seems to have resolved the issue for me on OSX

**Comment by s-a** [comment]
fixed with https://github.com/s-a/iron-node/releases/tag/v3.0.6
