### ISSUE TITLE
Application still doesn't start

### ISSUE THREAD

**Issue by oliversalzburg** [s-a/iron-node#107]
So I thought I'd give iron-node another try, because I had a suspicion why previous attempts to use it failed. 

However, now even the super simple test case from #56 doesn't do anything. I'm on Windows 10

**Comment by s-a** [comment]
Pretty hard to support with such less information. Seems your best Chance is to set some logs in iron-node boot process to figure out where the problem is. Alternative help is available at https://stackoverflow.com/questions/tagged/iron-node.

**Comment by oliversalzburg** [comment]
I would assume it has something to do with the use of `process.stdin.isTTY` and [MSYS](http://www.mingw.org/wiki/msys). When I start it from the Windows Command Prompt, it starts. But I'm also trying it on a different machine right now. Will confirm at home later.

**Comment by ndugger** [comment]
I'm having this issue as well. I'm on windows 10, and iron-node does nothing. I've had it work on OSX many times before.

How can I get you some helpful information about this?

**Comment by s-a** [comment]
@ndugger  you could put some Console Logs in https://github.com/s-a/iron-node/blob/master/app/index.js. this is the main process Code. The main shell entry point is here 
https://github.com/s-a/iron-node/blob/master/bin/run.js. would be interesting to see if the code spawns an electron instance.
