### ISSUE TITLE
Not able to get working

### ISSUE THREAD

**Issue by tony-gutierrez** [s-a/iron-node#109]
Installed -g 3.0.6 on osx.

First error was module mismatch. Got past that by going down some electron-rebuild hole. npm install electron-prebuilt or something. 

Now error is: Could not locate bindings file. 

tried --compile and back to the first error.

**Comment by s-a** [comment]
Very less informations. Since I cannot give support for Mac OS please use stackoverflow with iron-node Tag.

**Comment by tony-gutierrez** [comment]
npm install -g iron-node@2.x works on osx. Latest does not.
