### ISSUE TITLE
Incorrect .iron-node.js global config location for OS X in docs

### ISSUE THREAD

**Issue by rhiadj** [s-a/iron-node#110]
ironNode version : 3.0.7
operating system : OS X 10.10.5

**THE PROBLEM**

On this page:
https://github.com/s-a/iron-node/blob/master/docs/CONFIGURATION.md

... it states:

```
# on OS X
cd ~/Library/Application Support;
```

However I couldn't get this to work - looking at the source: https://github.com/s-a/iron-node/blob/master/app/config.js#L11

```
var osxHome = function () {
    return path.join(process.env.HOME, "Library/Preferences");
};
```

**POSSIBLE FIX**

It seems they are actually under a different path for OS X:

```
~/Library/Preferences
```

Creating the `~/Library/Preferences/iron-node/.iron-node.js` file worked as expected.

The docs need updating to point to the correct location.

**Comment by s-a** [comment]
Thanks
