### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by nvcwk** [s-a/iron-node#111]
I'm new to developing electron applications and I want to use iron-node to debug it. However, when i use iron-node to run my program, 

`sudo iron-node main.js`

I get this error:

`**TypeError: Cannot read property 'on' of undefined**`

Here is the development environment:
Electron: v1.1.3
Node: v4.4.7
Linux Mint: v17.1
iron-node: v3.0.6

Appreciate the help!

**Comment by s-a** [comment]
You cannot debug electron apps with iron-node. You can open devtools within your electron apps. https://github.com/s-a/iron-node/blob/35ae46ef7d129042ecbb85fd38dc36c4243ab42d/app/index.js#L108
