### ISSUE TITLE
Seems iron node can't find the file passed

### ISSUE THREAD

**Issue by bazjapan** [s-a/iron-node#112]
Thanks for ironnode.
I have just upgraded to the latest version from 2.1.14.
The same commands now no longer work for me though.

given this command
iron-node C:\Users\User1\javascript\test.js 
Iron node starts and immediately exits.

given the same path ran with node - the file runs correctly.

given a bogus file
iron-node C:\Users\User1\jnon-existing-file.js
Iron node starts and immediately exits.

finally given just iron-node with no path passed
iron node starts correctly

I can only assume that when a file path is passed it is being mangled somewhere along the line.

**Comment by s-a** [comment]
Does the shell console output some useful informations?

**Comment by bazjapan** [comment]
Unfortunately there is nothing reported in the console. I'm using a windows box - so I'm thinking the path is being misinterpreted.

**Comment by s-a** [comment]
So this might be a dublicate of #107. can you try native Windows shell? And what is a Windows Box?

**Comment by bazjapan** [comment]
thanks, I think I have got closer to resolving my problem. Version 2 installs to C:\Users\Harold\AppData\Roaming\npm\node_modules\iron-node
However the latest version installed to C:\Program Files\nodejs\node_modules\iron-node

I got it working by hard coding the path
in config.js line 61

`configFilename = "C:/Program Files/nodejs/node_modules/iron-node/.iron-node.js";

//configFilename = path.join( home(), "iron-node", ".iron-node.js"); // global config pathname

FYI: I am using nvm.

**Comment by s-a** [comment]
Ty for figuring this out. I never tested iron-node with nvm. In generel iron-node brings its own node engine it does not matter which node version is installed local so is there a way you can test npm? It seems you got many problems with iron-node regarding to nvm.
