### ISSUE TITLE
OSX - crashes immediately

### ISSUE THREAD

**Issue by schmod** [s-a/iron-node#114]
iron-node crashes immediately upon startup whenever I pass in a source file (ie. `iron-node myScript.js`).  It doesn't matter what the contents of the script are -- an empty file (or nonexistent) file will cause a crash.

Interestingly, if I run `iron-node` without arguments, it works fine.

OS X 10.11.6

![screenshot 2016-07-25 11 27 01](https://cloud.githubusercontent.com/assets/1102667/17106884/fd819fec-525a-11e6-9bfa-a5b29f8dbe5a.png)

[Crash report](https://gist.github.com/schmod/654df9ae9f37f82848f8891359bf5e60)

**Comment by s-a** [comment]
maybe a dublicate of #112 ? I updated electron version today.

**Comment by schmod** [comment]
I tried with 3.0.10, and had the same problem.  

It's sounding like #112 could be similar -- I'm not using NVM, but homebrew likely does something similar by installing node as a symlink

```
ls -la /usr/local/bin/node*
lrwxr-xr-x  1  29 Jul 25 11:13 /usr/local/bin/node -> ../Cellar/node/6.3.1/bin/node
```

I also install global packages to my home folder.  This is my `.npmrc`:

```
prefix=/Users/schmod/npm
```

---

**EDIT**: Ignore this comment, and see below.  NVM, NPM, Homebrew, and symlinks appear to be completely unrelated to this crash.

**Comment by schmod** [comment]
Looks like this is being caused by `autoAddWorkspace`.   I've opened a bug with the electron folks, because this is clearly broken on their side.

**Comment by schmod** [comment]
If others are experiencing this, and do not depend on live-editing, this bug can be worked around by creating an `.iron-node` config file either in your script's working directory, or preferences folder (platform-dependent -- `~` on Linux; `~/Library/Preferences` in OS X, APPDATA in Windows):

``` json
{
  "app": {
     "autoAddWorkSpace" : false
  }
}
```

**Comment by s-a** [comment]
Can you try with npm?

Am 26.07.2016 17:07 schrieb "Andrew Schmadel" notifications@github.com:

**Comment by s-a** [comment]
Ah ok did not read the rest of your posts 👍

**Comment by schmod** [comment]
I think this might be the same issue as #112 -- @bazjapan's workaround hard-coded the `.iron-node` configuration file that ships with this package into his configuration.

As far as I can tell, that file only exists to serve as an example -- it isn't typically used by the application, and doesn't provide a set of defaults (the actual defaults are [hard-coded](https://github.com/s-a/iron-node/blob/master/app/config.js#L36) into `config.js`).  

Hard-coding that configuration file only fixes the problem because `autoAddWorkspace` happens to be [disabled](https://github.com/s-a/iron-node/blob/master/.iron-node.js#L16) in that file.  NVM, NPM, and Homebrew appear to be unrelated to the actual underlying problem...

https://github.com/electron/electron/pull/6613 supposedly fixes the issue in Electron.  It seems like we just need to wait for the issue to be fixed upstream...

**Comment by abeninski** [comment]
Window is not reponding in Windows 8.1. Tried the `.iron-node` fix but didn't work. Downgraded to @v2
