### ISSUE TITLE
fails to stop on `debugger;` command

### ISSUE THREAD

**Issue by mattkime** [s-a/iron-node#116]
clone `https://github.com/mattkime/node-test-debuggers` and run `npm run iron-node`

the first time it worked. the second time i ran iron-node, it failed to stop on the `debugger;` command in the js file.

**Comment by jefffriesen** [comment]
This is a constant problem for me. Did anyone figure this out?

**Comment by vijayee** [comment]
I too share this issue

**Comment by s-a** [comment]
Just tested this with latest release on windows 10. Could you please retry with latest version? What OS are you using?

**Comment by s-a** [comment]
Will close this in favor of #119
