### ISSUE TITLE
A dynamic link library (DLL) initialization routine failed (bcrypt)

### ISSUE THREAD

**Issue by abeninskibede** [s-a/iron-node#117]
Hey guys,
Been using iron-node and it's awesome!

Got one issue when I installed bcrypt - iron-node can't start because of this:
![image](https://cloud.githubusercontent.com/assets/8179559/17689499/d2a21daa-6390-11e6-894b-8f1e3beb8c3e.png)

Using iron-node@3.0.11,  electron-v1.3.3-win32-x64. Windows 8.1

Anyone got any tips on this?

**Comment by krzysztofpniak** [comment]
I have exactly the same problem

**Comment by s-a** [comment]
Please take a look at https://github.com/s-a/iron-node/blob/master/docs/NATIVE-MODULES.md
