### ISSUE TITLE
iron-node not working with angular2-seed (typescript, gulp)

### ISSUE THREAD

**Issue by oehm-smith** [s-a/iron-node#118]
https://github.com/mgechev/angular2-seed

I performed the following:
- I found the gulp being run in `/usr/local/bin/gulp`.  I also tried `node_modules/gulp/bin/gulp.js` as specified in the iron node instructions.  Both give the same result.
- I modified `package.json` and added:
  
  "debug-gulp": "iron-node /usr/local/bin/gulp build.prod",

Where the normal command I'm running is:

```
"build.prod": "gulp build.prod --color --verbose",
```
- I ran the debug command:
  
  npm run debug-gulp

Electron opens and has stopped at the debugger line I added to the `build.prod` task and the message `paused in debugger` appears with the resume and step-over buttons .  I find gulp tasks called from this `build.prod` task and add breakpoints but after resuming they are never hit.  Also the `paused in debugger` text with the resume and step-over buttons is still visible however it seems to be running as the call stack shows nothing and says `not paused`.  The effect of pressing the pause button only seems to be to make that pause button unavailable.

Stepping has the same problem as resuming.

It seems to get lost in la-la land.  Next I put three sequential `debugger` statements and expect it to stop on each one.  However like before, hitting resume puts Electron into the weird paused-but-not-paused state.

The debugger line can be anywhere and it will always stop this first time.

Another interesting aspect of what I'm seeing is that if I try to add a breakpoint to a `.js` file, the corresponding `.ts` file is switched into view and the breakpoint appears in there.

I'm running the latest Chrome - Version 52.0.2743.116 (64-bit).

Is typescript not supported, or Is all this a bug, feature or is there something else I need to do to get iron node running (I've never used it before and I'm reasonably new to the .js / node world)?

**Comment by s-a** [comment]
I never debugged global gulp installation. I always prefer local installation. Here is the way I am debugging gulp tasks...

```
)npm run debug-gulp build.prod

> temp@1.0.0 debug-gulp c:\Temp
> iron-node node_modules/gulp/bin/gulp.js "build.prod"
```

![image](https://cloud.githubusercontent.com/assets/1270662/18879090/633b31fe-84d3-11e6-8cf9-e8698f47e69c.png)

I think the only difference is that I append additional gulp parameters to the `npm run debug-gulp` command

```
package.json
{
  "name": "temp",
  "version": "1.0.0",
  "description": "",
  "main": "gulpfile.js",
  "directories": {
    "test": "test"
  },
  "dependencies": {},
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-util": "^3.0.7"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "debug-gulp": "iron-node node_modules/gulp/bin/gulp.js"
  },
  "author": "",
  "license": "MIT"
}
```

Regarding to typescript : This is not supported but it might possible that there are "hidden" features in Chrome.
