### ISSUE TITLE
iron-node > 2.2.15 makes unicorns cry => doesn't work on OSX

### ISSUE THREAD

**Issue by dtothefp** [s-a/iron-node#119]
After looking through your issues looks like this may be Node installed via `nvm` and/or OSX related. Putting this up hoping to get any helpful advice. Relates back to issue https://github.com/s-a/iron-node/issues/106 which never ended up resolving my issue. I created a sample repo to show problems I'm having 

https://github.com/dtothefp/iron-node-makes-unicorns-cry
##### Summary
- `npm i -g iron-node@2.2.15`
  - everything works great
  - uses `electron-prebuilt@0.36.12`
- `npm i -g iron-node@2.2.16`
  - :-(( warns about devtools detached
  - might catch on first breakpoint in `gulp` task but won't catch subsequent
  - won't catch any breakpoints in `./test.js`
  - uses `electron-prebuilt@0.37.8`

```
`which iron-node` #/Users/xxx/.nvm/versions/node/v6.3.1/bin/iron-node
cd /Users/xxx/.nvm/versions/node/v6.3.1/lib/node_modules/iron-node/node_modules
npm i electron-prebuilt@0.36.12 #this is the version in iron-node@2.2.15
# this works again :-))
```
- `npm i -g iron-node@latest`
  -  :-(( doesn't catch on any breakpoints in the `gulp` task or `./test.js`
  - uses `electron-prebuilt@1.3.5`

**Comment by s-a** [comment]
Yes nvm seems a good source for headache when using iron-node on osx.

**Comment by dtothefp** [comment]
@s-a that's a bummer. do you think [N](https://github.com/tj/n) would be better?

**Comment by s-a** [comment]
NVM got never my attention. As far as I can see nvm handles differnt node versions, but iron-node comes bundled with its own node core. So it its not necessary to install iron-node with nvm.

**Comment by s-a** [comment]
could you please try latest version? i tweaked a few things. https://github.com/s-a/iron-node/blob/1018b51a1b018d69fe51d411766a925bb3c58de2/app/index.js#L143-L145
