### ISSUE TITLE
Application takes 100% CPU and is unresponsive

### ISSUE THREAD

**Issue by hoschi** [s-a/iron-node#120]
Hi,

version 2.2.15 works, but bigger versions freezes like described in the subject. I tried to take the latest version with electron-prebuilt@0.36.7, but then iron-node doesn't start at all. Here are my system description:

Arch Linux
node version: 6.3.1
npm version: 3.10.3

Perhaps you have an idea what causes this issue?

**Comment by s-a** [comment]
No sorry . Do you start a special script for debug session or just `$ iron-node;` ?

**Comment by hoschi** [comment]
just `iron-node`

**Comment by hoschi** [comment]
fixed with 3.0.17, but only after I did `rm -rf ~/.config/iron-node-app`

**Comment by s-a** [comment]
Thanks for reporting this :+1:
