### ISSUE TITLE
command + w closes iron-node even when iron-node is behind another window

### ISSUE THREAD

**Issue by stoplion** [s-a/iron-node#122]
1. when iron node window is behind another window (i.e. browser window)
   //iron node window is no longer focused
2. A tab is closed on that browser window via command + w
3. iron-node closes

[![https://gyazo.com/dce6259d3a71f0edce35149b1d156c48](https://i.gyazo.com/dce6259d3a71f0edce35149b1d156c48.gif)](https://gyazo.com/dce6259d3a71f0edce35149b1d156c48)

**Comment by drew-wallace** [comment]
Super annoying.
