### ISSUE TITLE
How to pass command to nodejs?

### ISSUE THREAD

**Issue by SerkanSipahi** [s-a/iron-node#123]
Env:
iron-node v3.0.15
mac osx el-capitan v10.11.6

I want to start iron-node with arguments for nodejs but it will not work ! It throw an error:

``` bash
iron-node babel-node node_modules/.bin/_mocha  -- test
```

iron-node try to load `babel-node` but that is not what i expected. 
iron-node should call `babel-node node_modules/.bin/_mocha  -- test` this as additional node arguments.

Error:

``` error
Error: ENOENT: no such file or directory, open '/Projects/babel-plugin-transform-decorators-legacy/babel-node'

  - Error
  - ELECTRON_ASAR.js:178 Object.module.(anonymous function) [as openSync]
    ELECTRON_ASAR.js:178:20

  - ELECTRON_ASAR.js:511 Object.fs.readFileSync
    ELECTRON_ASAR.js:511:29

  - app.js:254 boot
    [lib]/[iron-node]/app/app.js:254:16

  - app.js:274 
    [lib]/[iron-node]/app/app.js:274:1

```

**Comment by s-a** [comment]
Here are some efforts to debug babeled code with `iron-node` https://github.com/s-a/iron-node/issues/54
