### ISSUE TITLE
All good things come to an end..

### ISSUE THREAD

**Issue by bazjapan** [s-a/iron-node#124]
I felt compelled to drop you a line to say thank you for your work on this project.
much appreciated.

**Comment by vkuehn** [comment]
yes I can only say thanks a lot too !
you mentioned on npm "
 At the end of 2016 a lot of solutions for debugging appeared at the sky of JavaScript."
I wonder what actually is a good visual debugger for node apps ?

**Comment by fetchTe** [comment]
I also would like to say thank you @s-a. Iron-node has been been one of the most instrumental and valuable tools in my pipeline. Thanks a million and best wishes your future endeavors.

**Comment by s-a** [comment]
Thanks @all! The new kid is back :baby_chick: @vkuehn I realy like Visual Studio Code debug features. They are very powerful. But I miss some console support features there. This is the reason i revived `iron-node` at https://github.com/s-a/iron-node/pull/126. I would also like to use https://nodejs.org/api/debugger.html#debugger_v8_inspector_integration_for_node_js but It is pretty uncomfortable right now.

I recently opened https://github.com/Microsoft/vscode/issues/19396. Maybe the creators are willing to implement some `iron-node` features regarding console development.

**Comment by fetchTe** [comment]
I agree @s-a, while VS debugging features are nice I hate that it vendor-locks you in, and nodes native debugger leaves much to be desired. Put simply, `iron-node` in my opinion is currently the best option available and I'm happy to see it's not dead yet.
