### ISSUE TITLE
Run this in the web browser

### ISSUE THREAD

**Issue by zwhitchcox** [s-a/iron-node#129]
Is there any way to run this in the web browser? I only have access to the command line and web browser

**Comment by snoblenet** [comment]
You've described the default approach to debugging Node, as per:

https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27

Iron-Node is about moving some of that functionality from Google Chrome's DevTools panel to a standalone app.
