### ISSUE TITLE
Keyboard shortcuts for copy and paste does not work on OS X

### ISSUE THREAD

**Issue by artem-russkikh** [s-a/iron-node#13]
For example I can't copy and paste something, close electron app by command-w (#12)

**Comment by s-a** [comment]
Selecting text and pressing `ctrl+c` within the info window works for me on Windows. Do you experience another behavior on OS X?

**Comment by artem-russkikh** [comment]
@s-a Command+C (copy), Command+V (paste), Ctrl+C, Ctrl+V doesn't do anything on OSX

**Comment by jefffriesen** [comment]
Confirming on another OS X machine (Yosemite). command-c and command-v does not work, nor is it available through the contextual menu. Copy and paste does work properly in Chrome's inspector.

**Comment by s-a** [comment]
@jefffriesen  this is also a ticket at https://github.com/atom/electron/issues/525

**Comment by s-a** [comment]
Can any one checkout `npm install iron-node@1.5.23 -g;` pls and give feed back for mac os x ? This should solve the issue regarding the webview. We should open a new ticket context menu in devtools.

**Comment by artem-russkikh** [comment]
@s-a Command-C, Command-V is working now

**Comment by s-a** [comment]
:+1: ty hope they will fix context menu  for osx soon.
