### ISSUE TITLE
Electron failed to install correctly, please delete node_modules/electron and try installing again

### ISSUE THREAD

**Issue by varnitsaini** [s-a/iron-node#131]
### Description

I am using OSX and I have followed the instructions as given to install iron-node

`npm install -g iron-node`

But i am getting error as 

> throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')

**Error log(s):** 
My code is in index.js and when i run the command ` iron-node index.js ` i am getting following error, i guess it doesn't have to do with the code present in index.js instead iron-node is not fulfilling the proper dependency

> 
> /usr/local/lib/node_modules/iron-node/node_modules/electron/index.js:9
>   throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
>   ^
> 
> Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
>     at Object.<anonymous> (/usr/local/lib/node_modules/iron-node/node_modules/electron/index.js:9:9)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/usr/local/lib/node_modules/iron-node/bin/run.js:2:16)
>     at Module._compile (module.js:571:32)
>

**Comment by s-a** [comment]
Sorry I have no OSX available to support. May be the best way is to ask at SO to reach more users who could help.

**Comment by s-a** [comment]
I recently upgraded electron dependency version. Any news about your issue with latest iron-node version?

**Comment by s-a** [comment]
I' am closing this issue as it has gone thirty days without activity. In my experience if an issue has gone thirty days without any activity then it's unlikely to be addressed. In the case of bug reports, often the underlying issue will be addressed but finding related issues is quite difficult and often incomplete.

If this was a bug report and it is still relevant then I encourage you to open it again as a new issue. If this was a feature request then you should feel free to open it again, **or even better open a PR**.

To reach more support it might be a good idea to post your questions at https://stackoverflow.com/questions/tagged/iron-node.

**Comment by jsaucedo** [comment]
@varnitsaini Hey did you find a solution for this issue?

**Comment by itsmasud** [comment]
See in the message that it is saying that there is a directory where the global npm package is installed. In your case it is inside:
**/usr/local/lib/node_modules/iron-node/node_modules/**

So go to that directory and delete all the directory named prefixing electron.

Now run 
**npm install -g react-devtools**


After that you are ready to roll.

To start the dev tools, write the following command.

**react-devtools**
