### ISSUE TITLE
[feature request] Debugging without writing debugger

### ISSUE THREAD

**Issue by quantuminformation** [s-a/iron-node#132]
Is this possible? I find it easy to navigate and place breakpoints in chrome.

**Comment by s-a** [comment]
Yes. Hope this doc helps https://github.com/s-a/iron-node/blob/master/docs/MASTER-THE-BREAKPOINTS.md

**Comment by quantuminformation** [comment]
Found it! Is there a way to differentiate 2 files without guessing which one is in memory, with `cmd+p`
![image](https://user-images.githubusercontent.com/216566/27384481-ee4cc476-5686-11e7-81d5-2fe506de00cc.png)

**Comment by s-a** [comment]
Unfortunately not. I know it is anoying :/

**Comment by quantuminformation** [comment]
thx anyway
