### ISSUE TITLE
contextify.node was compiled against a different Node.js version using NODE_MODULE_VERSION 48

### ISSUE THREAD

**Issue by achimbode** [s-a/iron-node#134]
### Description

I installed iron-node as suggested with `sudo npm install -g iron-node` to debug my mocha testcases and it starts node-iron but throws a NODE_MODULE_VERSION error (details below).

### Steps to Reproduce

1. install iron-node version 3.0.20 globally
2. set "iron" script in package.json to
 `"iron": "iron-node ./node_modules/mocha/bin/_mocha --compilers js:babel-core/register --require ./test/test_helper.js \"test/**/*@(.js|.jsx)\""`
3. npm run iron

**Expected behavior:** iron-node will start in a window and be ready for debugging

**Actual behavior:** iron-node starts in a window and throws the indicated NODE_MODULE_VERSION error

**Reproduces how often:** always

**Error log(s):** 
Error: The module '/Library/WebServer/Documents/myproject/node_modules/con  textify/build/Release/contextify.node'
  was compiled against a different Node.js version using
  NODE_MODULE_VERSION 48. This version of Node.js requires
  NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
  the module (for instance, using `npm rebuild` or`npm install`).
  
  - ELECTRON_ASAR.js:173 process.module.(anonymous function) [as dlopen]
    ELECTRON_ASAR.js:173:20

### Version(s)

- iron-node version: 3.0.20
- node version: 6.11.2
- local contextify version: 0.1.15
- local mocha version: 3.5.3

### Remarks

I tried to recompile everything within my local node_modules with

  `achimbode@propellermac /Library/WebServer/Documents/myproject $ iron-node --compile=.`

as suggested [https://github.com/s-a/iron-node/issues/58], but it just says
  userhome /Users/achimbode/.iron-node
  exist

and the problem remains.

I tried to change the version node/5.9.1, but then my project won't run. Just to be sure, I also changed to node/8.4.0, but that won't solve the problem.

I tried to recompile contextify as suggested in the error log with

  `npm rebuild /Library/WebServer/Documents/voting-client/node_modules/contextify`

but it doesn't help my case. Same with install...

**Comment by s-a** [comment]
The goal of `iron-node --compile=.` was to compile a paralel version of native modules so we can use `node` even we reompiled. I just faced the same problem and had more success using `electron-rebuild -v 2.0.0 -f` where `-v` is the current electron runtime environment of latest `iron-node` version.
