### ISSUE TITLE
Developer tools zooming settings are not saved

### ISSUE THREAD

**Issue by unlight** [s-a/iron-node#2]
Subj.

Is it Electron bug?

**Comment by s-a** [comment]
Unfortunately I do not know what you mean exactly. Can you please provide more details?

**Comment by unlight** [comment]
1. Run
   ![](http://i.gyazo.com/2412dd418cacfea38c979332784992cf.png)
2. Zoom (Ctrl + +)
   ![](http://i.gyazo.com/0a406e135610af09acf616a6067eb347.png)
3. Exit and run again

Zooming settings are not saved, it is same as on initial run (step 1).
But chrome keeps these zooming settings after restart.

**Comment by s-a** [comment]
Ok thanks I got it :smiley: . This behavior is annoying but does not belong to my code. Can you please research at https://github.com/atom/electron/issues and keep us up-to-date here?

**Comment by s-a** [comment]
@unlight  by the way did you know you can simply press `ctrl+r` to reload your code? Maybe this is a little workaround for you.

**Comment by s-a** [comment]
While I noticed some other inconsistencies I submitted an issue to https://github.com/atom/electron/issues/2324 and reopened this issue.
