### ISSUE TITLE
Running iron-node $(which **) commands fails

### ISSUE THREAD

**Issue by jhicken** [s-a/iron-node#21]
Hey I'm on osx. I haven't dug in here super deep. But... whenever I try to debug global modules that run tasks I get a stack of errors. I have tried karma and gulp. I don't know if I'm just doing it wrong. Or if there is something to be fixed. 

iron-node $(which gulp) task-name
iron-node $(which karma) start

I do love how much quicker this is than node-inspector.

**Comment by s-a** [comment]
This is interesting! I never tried this. ironNode needs a JavaScript file to process as the first parameter. I am shure there exists something like gulp.js. I am not shure if `which` resolves it to the main JavaScript file or an OS shell command file. Can you find this out?

**Comment by s-a** [comment]
If nothing works ... You can simply create an own JavaScript file. Require gulp there and execute the task you whish. Then debug your new JavaScript file. This should work. Maybe karma is not trivial as that.

**Comment by s-a** [comment]
The `which` command on windows resolves to a bash script

```
C:\Users\Stephan\AppData\Roaming\npm\iron-node
C:\Users\Stephan\AppData\Roaming\npm\iron-node.cmd
```

which contains.

``` bash
#!/bin/sh
basedir=`dirname "$0"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/node_modules/iron-node/bin/run.js" "$@"
  ret=$?
else 
  node  "$basedir/node_modules/iron-node/bin/run.js" "$@"
  ret=$?
fi
exit $ret
```

So you have definitely to call corresponding JavaScript file. Please keep us up-to-date with your progress.

**Comment by s-a** [comment]
@jhicken heads up to https://github.com/s-a/iron-node/issues/22! You can try remove the v8flags dependency in gulp as described in my PR. Hope this helps. 

![image](https://cloud.githubusercontent.com/assets/1270662/8923471/843f174a-34f1-11e5-8e15-7746ea5b90be.png)

**Comment by jhicken** [comment]
That looks to work thanks @s-a

**Comment by s-a** [comment]
They updated the code. So you can simply reinstall gulp.
