### ISSUE TITLE
Module did not self register

### ISSUE THREAD

**Issue by robrichard** [s-a/iron-node#24]
Using node v0.10.33

![screen shot 2015-07-29 at 5 15 55 pm](https://cloud.githubusercontent.com/assets/3814096/8970084/8e3d4bb6-3615-11e5-8f67-8e28670377bd.png)

**Comment by s-a** [comment]
Internal it uses node 2.3.1. Sounds like something regarding to https://github.com/s-a/iron-node/blob/master/docs/NATIVE-MODULES.md. Can you find out which module it tried to load? Is there public code I can test?

**Comment by s-a** [comment]
Contextify sound s like something which needs to be recompiled.

**Comment by s-a** [comment]
pls check out updated https://github.com/s-a/iron-node/blob/master/docs/NATIVE-MODULES.md. I will close this issue until there is no more feedback.
