### ISSUE TITLE
Custom CSS for the document area

### ISSUE THREAD

**Issue by gritzko** [s-a/iron-node#25]
Hi!
I am runnning unit tests in Iron Node.
The test reporter (npm:tape-dom) puts OK/FAIL records into the DOM, which is handy.
Unfortunately, the DOM has no CSS to format those records right.
Is possible to add custom CSS somehow?

Thanks!

**Comment by s-a** [comment]
Fascinating :smiley: 
You should have the full control to `window` and `document` variables. From here you can load external CSS or inject styles to the page.

It is also possible to load a complete different HTML file. 
`window.location.href` should work.
I would like to see a screenshot :+1:

**Comment by gritzko** [comment]
https://github.com/gritzko/tape-dom/commit/c33bb75d14aa9586bb40c5946871a95d97d54b97
This trick works for Chrome, but not for IronNode.
Not sure about the reason yet.
![chrome-tape](https://cloud.githubusercontent.com/assets/81581/8985561/af22f92c-36e0-11e5-8436-f5d6651092aa.png)
![iron-tape](https://cloud.githubusercontent.com/assets/81581/8985564/b127637a-36e0-11e5-8681-e2efcb299049.png)

**Comment by s-a** [comment]
This works for me....

``` css
/*custom.css*/
body{
    color:cyan;
}
```

``` javascript
// inject.js
var path = require("path");

// CSS injection
var style = document.createElement("style");
style.setAttribute('type', 'text/css');
style.innerHTML = "body{background-color:yellow}";
window.document.head.appendChild(style);


// external CSS file
var style2 = document.createElement("link");
style2.setAttribute('rel', 'stylesheet');
style2.setAttribute('type', 'text/css');
style2.setAttribute('href', 'file://' + path.join(__dirname, "custom.css"));
window.document.head.appendChild(style2);
```

``` bash
iron-node inject.js
```

![image](https://cloud.githubusercontent.com/assets/1270662/8986075/b65d87e4-36da-11e5-97d5-98cfe3422490.png)

Does it fit your needs?

**Comment by gritzko** [comment]
Local files work for me too, thanks.
I guess, the issue is about the MIME type GitHub sets for the file.
