### ISSUE TITLE
Cannot use harmony switches on the command line

### ISSUE THREAD

**Issue by cscalfani** [s-a/iron-node#29]
I'm running `iron-node --harmony_arrow_functions index.js` and it tries to load the parameter as a file.

**Comment by s-a** [comment]
This goes conform to the current command line description at https://github.com/s-a/iron-node#debug-session. So far there is no mechanism to pass v8 switches via commandline,

Not tried yet but one of this should do the job as described at  https://iojs.org/api/v8.html#v8_setflagsfromstring_string:

``` javascript
var v8 = require('v8');
v8.setFlagsFromString('--harmony-arrow-functions');
```

``` javascript
var flags = require('v8-flags').flags;
flags.harmony_arrow_functions(true);
```

Available flags are described at: https://github.com/thlorenz/v8-flags/blob/master/flags-0.11.md.
But cannot find `harmony-arrow-functions` and no time today for further research. Can you investigate further?

**Comment by cscalfani** [comment]
Unfortunately, neither worked. And BTW, the name of the flag has underscores not dashes. (That confused me too.)

Any ETA on passing V8 flags via command line?

**Comment by s-a** [comment]
Not really, 
forthcoming feature is a [Plugin system](https://github.com/s-a/iron-node/blob/master/docs/PACKAGES.md) which i' m currently testing against a dark ui theme. 
From a plugin you could set up such v8 flags if they would work. Have you tried a flag which is listed at https://github.com/thlorenz/v8-flags/blob/master/flags-0.11.md?

**Comment by s-a** [comment]
Seems they solved the problem. Can you try to setup v8 and then requiere your es6 code via separate js file? 

https://github.com/atom/electron/issues/2118

**Comment by s-a** [comment]
@cscalfani I got it 
![image](https://cloud.githubusercontent.com/assets/1270662/9044412/bc9e29f2-3a1c-11e5-9f0c-d0c664b4cdb4.png)

I will build something that solves this issue. as a workaround you can put this line into the app [ready event](https://github.com/s-a/iron-node/blob/master/app/index.js#L19).

``` javascript
app.commandLine.appendSwitch('js-flags', '--harmony-arrow-functions');
```

**Comment by s-a** [comment]
@cscalfani https://github.com/s-a/iron-node/releases/tag/v1.5.22

Please let us know if this works for you.

**Comment by cscalfani** [comment]
Thank you!!! I'm excited to use this but I have a couple of questions that the docs don't quite answer.

First off, the doc say that on OSX I'm looking for the `iron-node` directory under `~/Library/Application Support`. There's already directory there called `iron-node-app`. Is this the directory you were referring to or do I need to create the other directory?

Second question, can you provide the example format for the `.iron-node.js` file (preferably in the documentation so others can benefit from this)?

Thanks again for working so quickly on this.

**Comment by s-a** [comment]
You need to create the new folder. `iron-node-app` is some thing electron related. https://github.com/s-a/iron-node/blob/master/.iron-node.js is linked in the docs, but I have just seen that this is not clear enough :+1:

**Comment by cscalfani** [comment]
Works!!! Thanks.
