### ISSUE TITLE
Windows line endings cause trouble on OSX

### ISSUE THREAD

**Issue by tqwhite** [s-a/iron-node#3]
I changed run.js to use Unix line-feed and it works.

**Comment by mgcrea** [comment]
:+1: broken on OSX.

```
$ iron-node
env: node\r: No such file or directory
```

**Comment by cuongvo** [comment]
Ran into this issue too.

:set ff=unix should fix if you're using vim

**Comment by s-a** [comment]
@tqwhite @mgcrea @cuongvo Thanks for reporting this issue. Pointing to the solution was very helpful. Just published v1.0.2 to NPM.
