### ISSUE TITLE
process.stdout.write does not output to DevTools console?

### ISSUE THREAD

**Issue by krohrsb** [s-a/iron-node#30]
The app i was testing with uses bunyan which logs to the console. However when running with iron-node the console/stdout is suppressed for some reason.

**Comment by s-a** [comment]
Did you checked the devtools console?

**Comment by krohrsb** [comment]
a normal `console.log` in the app does output to the devtools console. However using `bunyan` with (bunyan-format)[https://github.com/thlorenz/bunyan-format] as the output stream does not. Though of course `bunyan` normally does log the output.

**Comment by s-a** [comment]
Not very beautiful but I got output to terminal console

![image](https://cloud.githubusercontent.com/assets/1270662/9043155/b83900f2-3a13-11e5-8326-795bb8c87334.png)

I have noticed some other things regarding to that as described at https://github.com/atom/electron/issues/2390

**Comment by s-a** [comment]
@blackbarn do you see any output like on my console? Otherweise I would like to change the issue title.

**Comment by s-a** [comment]
My guess is that the isbrowser method does not work correct within electron environment.

https://github.com/trentm/node-bunyan/blob/master/lib/bunyan.js#L407 can you clarify this?

**Comment by krohrsb** [comment]
Sorry, I was preoccupied there for awhile. I'm glad it seems to be working and sorry for causing any problems. When I have time i'll dig into my implementation a bit more to see if I can find my issue. Thanks for all your work on the project!

**Comment by s-a** [comment]
Absolutely no problem, feel free to submit issues! Well I am not shure it isjust a guess. So if you want. Would be nice to keep us up-to-date  here.

**Comment by Bargs** [comment]
I'm having the same issue. Logs that are piped to `process.stdout` do not show up in my terminal or Devtools console. I do successfully get logs when using the regular `node` process. Any ideas what might be going on?

**Comment by s-a** [comment]
Can you publish a reproducable code example?

**Comment by Bargs** [comment]
If you clone the Kibana repo (https://github.com/elastic/kibana) and run `node ./src/cli` you'll see some log output. If you run `iron-node ./src/cli` there will be no log output in the terminal or Devtools console.

Note that these logs are ultimately getting sent to process.stdout in `./src/server/logging/LogReporter.js`

**Comment by s-a** [comment]
Ty, I will check this out this weekend .
Am 12.11.2015 00:12 schrieb "Matt Bargar" notifications@github.com:

**Comment by s-a** [comment]
Sir @blackbarn I will not find time this we again :\   pls can u try https://github.com/s-a/iron-node/issues/60#issuecomment-149783292. there where a lot of improvements by the creators of Electron regarding console log. Hope this will help u. You can try to upgrade electron within iron -node

**Comment by Bargs** [comment]
Hi @s-a , I tried upgrading Electron, unfortunately it didn't make a difference.

**Comment by s-a** [comment]
@Bargs ty for the attempt. Could you please open an issue at the electron repo?

**Comment by Bargs** [comment]
Yes I'll try to get to that this weekend. Thanks!

**Comment by s-a** [comment]
@Bargs  I plan a new release this weekend. Any news about this topic?

**Comment by Bargs** [comment]
Hi @s-a. I have to admit this slipped my mind. I haven't been working with iron node much recently, if I get back into it I'll make sure to follow up.

**Comment by willhoag** [comment]
Hi! I'm having the same issue. Any updates on this? I'm happy to make an issue on the electron repo, but haven't used electron and wouldn't know how to properly describe what we think is happening.

**Comment by s-a** [comment]
I believe you experience this issue when using console output log streams. I never used this. But it seems you have reproducable code there?

**Comment by willhoag** [comment]
Yeah, when using streams process.stdout like this:

``` js
process.stdout.write("doesn't work")
console.log('works')
```

**Comment by s-a** [comment]
Ok. Could you plz send an issue to the creator s of electron?

**Comment by willhoag** [comment]
Per https://github.com/atom/electron/issues/3979#issuecomment-168852528 to get output in the console via `process.stdout.write` it sounds like this ought to do it:

``` js
process.stdout.write = console.log.bind(console);
```

Can you confirm?

**Comment by s-a** [comment]
@willhoag thanks for clarify! Yes it sounds very reasonable. You can test if this works when you put this code into your startup script. I will implement the code into iron-node core if this works for you.  I would test it but realy never used `process.stdout.write`.

**Comment by s-a** [comment]
![image](https://cloud.githubusercontent.com/assets/1270662/12108862/670e131a-b37c-11e5-8a8d-d27943c65c87.png)
just tested this with kibana by @Bargs :+1: 

Will publish this pice of code with the next release. Ty @willhoag

**Comment by s-a** [comment]
Please use https://github.com/s-a/iron-node/releases/tag/v2.1.4 for further testings.

**Comment by willhoag** [comment]
Confirming that the update produces output using process.stdout.write in the console. Thx!
