### ISSUE TITLE
dialog buttons unreachable when error stack trace is very long

### ISSUE THREAD

**Issue by BerkeleyTrue** [s-a/iron-node#31]
Hey @s-a, another awesome project!

When I first launched, I get this error from my project (it doesn't like iron-node very much). The stack trace is so long I couldn't see the buttons on the bottom and there is no scroll bar to navigate down.

Hitting enter navigates me past this error.

![ironnode_v1_5_23_and_new_issue_ _s-a_iron-node](https://cloud.githubusercontent.com/assets/6775919/9068752/2ddbaeb4-3a9a-11e5-96fe-89bc49b52699.png)

**Comment by s-a** [comment]
Hi @BerkeleyTrue  I do not think so, fact is that ironNode loves your code unconditionally  :smiley_cat: 

Regarding the message box...  
This is true. This dialog is a relict from the main process development. It will change to a desktop notfication with a hint to detailed error message in devtools console or terminal console in future.

**Comment by s-a** [comment]
@BerkeleyTrue I am experimenting with a toaster 
![image](https://cloud.githubusercontent.com/assets/1270662/9095467/a1716d5a-3bb7-11e5-999b-ff6de78dace2.png)

Are you willing to try the branch https://github.com/s-a/iron-node/tree/notify on mac ?
