### ISSUE TITLE
does this work with Meteor?

### ISSUE THREAD

**Issue by faceyspacey** [s-a/iron-node#32]

**Comment by s-a** [comment]
:laughing: you already asked this at #1  
Mr. @faceyspacey :smile:  
Basically it works with a meteor debug build. [As described](https://github.com/s-a/iron-node/issues/1#issuecomment-124917929) I am not a meteor expert. So any help there is very welcome!

**Comment by s-a** [comment]
@faceyspacey do you know some experts who could help? I have updated current status at #1. which is not bad I think.

**Comment by faceyspacey** [comment]
...lol, i thought i had seen another new alternative to node inspector...To be honest, I posted so quickly these questions because I know this sorta stuff isn't my forte. I don't know anyone specifically, but if there is one guy this is for, it's Arunoda, basically the most prolific meteor package developer. i'll forward it to him.

**Comment by s-a** [comment]
I d like to see this work with meteor very much, but do not have the time get deep knowledge there. I think the last step to success is to find out how to trigger the meteor prebuilds instead of running a meteor debug build.
