### ISSUE TITLE
(require.main === module) is false for the main module loaded

### ISSUE THREAD

**Issue by mik01aj** [s-a/iron-node#34]
This is annoying when debugging scripts that can be used as both a command-line utility and a Node module.

**Comment by s-a** [comment]
Never used this before. I think this happens because we require every module instead of starting them directly. Not sure if this could (should) be overwritten.

What do you think? 

Just a notice for me:  
https://nodejs.org/api/modules.html#modules_accessing_the_main_module

**Comment by s-a** [comment]
:+1: found a way.
`require.main` is over-writable like this.  

```
require.main = require("module")._cache["C:\\Users\\Stephan\\AppData\\Roaming\\iron-node\\node_modules\\iron-node-zerodarkmatrix-theme\\index.js"]
```

Where are you experiencing such a problem? Can you please provide a simple use case? What do you think ? should we overwrite this?

**Comment by s-a** [comment]
Can you pls test this in your start up script. 
reassign require.main if electron run-time environment was detected. This can be done by checking `process.argv[0]`.  

I will close this issue unless there comes no more feedback. We can re open this at any point.

**Comment by mik01aj** [comment]
This worked:

```
if (process.argv[0].indexOf('Electron') !== -1) {
    require.main = require("module")._cache[__filename]
}

if (require.main === module) {
    // ...
```

So I guess that to make it work in `iron-node` you just need to inject this line into the main file:

```
require.main = require("module")._cache[__filename]
```

**Comment by s-a** [comment]
Not trivial. So far I think its better to leave any file untouched. Will research for a solution. Good to know we have a workaround.

**Comment by s-a** [comment]
@mik01aj isnt it the same effect when you run your code through mocha tests or something like this? Still not realy sure we should touch require.main.

**Comment by mik01aj** [comment]
When I run mocha tests, the `main` is some module from Mocha. I do this check only in my main `cli.js` module, so that if it's being run directly, it runs whatever logic it has. But when I `require('cli.js')` from my tests, I don't want the module to display the welcome message, show the prompt and wait for user input. I just want it to expose some functions so that I can use it in other modules. With this approach, I can also create a new package that will `require('myOldPackage/cli.js')` to do something more complex.

For example, `npm` does this too: https://github.com/npm/npm/blob/932b86e2e9930eb5d4dc0f0853ec627870013786/lib/npm.js#L473

**Comment by s-a** [comment]
I checked some methods to initiate a changed behavior of `require.main`. Unfortunately alle of them cause critical side effects. 

``` javascript
if (process.argv[0] && process.argv[1] && process.argv[0].toLowerCase().indexOf('electron') !== -1 && process.argv[1] === __filename) {
    require.main = require("module")._cache[__filename]
}
```

We have to put this piece of code into our main scripts to master this issue.
