### ISSUE TITLE
process.argv value is invalid

### ISSUE THREAD

**Issue by mik01aj** [s-a/iron-node#36]
I created 2 little files:

a.js:

```
require('./b');
console.log('a:', process.argv);
```

b.js: 

```
console.log('b:', process.argv);
```

This is what happens when I run it in node (with or without the debugger):

![screenshot 2015-08-07 11 31 07](https://cloud.githubusercontent.com/assets/3027415/9132984/f9ed60f6-3cf7-11e5-8643-518b3a642165.png)

This is what I see when I run it in iron-node:

![screenshot 2015-08-07 11 29 43](https://cloud.githubusercontent.com/assets/3027415/9132986/06d38e3a-3cf8-11e5-964e-c0c6229eb189.png)

I expect to see the same values as in Node.

Note that this can be a nasty bug to some libraries that rely on `process.argv[1]` being the full path to the main file. For example, [ratify loops infinitely when it sees `process.argv[1]` without slashes](https://github.com/mac-/ratify/issues/40).

**Comment by s-a** [comment]
Sorry I am on the run... 
In short: You expect the full path to `a.js` right?

I think this regards to this code 
https://github.com/s-a/iron-node/blob/6ac6b398fdf8eda8db614b9fb651f1ab8ec9266d/app/app.js#L61

Will check this out soon. Maybe you can see something there?

**Comment by mik01aj** [comment]
In this case, yes. I expect exactly the same result as in Node (with or without debug, it's not very important).

In node debugger it looks tricky, because the modules get a different value than what is accessible from the debugger. What's important is the value that the modules get.

**Comment by s-a** [comment]
@mik01aj just published a new version via npm. Please let me know if this works for you.

**Comment by mik01aj** [comment]
Still the same, using `iron-node@1.5.27`. Btw, this is what npm says; the app title bar says it's `v1.2.16`.

<img width="1110" alt="screenshot 2015-08-10 09 57 02" src="https://cloud.githubusercontent.com/assets/3027415/9162492/47cba7ec-3f46-11e5-9c7f-9ed5da126a60.png">

**Comment by s-a** [comment]
This indicates you are using old code.
Title bar shows `package.json.version`

This is what I get at:

``` bash
C:\test>iron-node test.js
```

![image](https://cloud.githubusercontent.com/assets/1270662/9163637/df955ec0-3f4a-11e5-9843-3687d2c9dfa4.png)

Can you research and give feedback what is causing this, just to be shure that this is not a general issue.

**Comment by mik01aj** [comment]
I figured it out: before I started using `nvm`, my `npm` installed packages to `/usr/local/lib/node_modules` and their binaries to `/usr/local/bin`. After I started using `nvm`, all packages got installed to `~/.nvm/versions/node/v0.12.7/lib/node_modules` and the binaries to `~/.nvm/versions/node/v0.12.7/bin`. The problem was, that `/usr/local/bin` was first in the `$PATH` variable, so I was using the package that was installed for an older version of Node.

So now I'm really using `1.5.27` and I'm happy to say that it works now! Thanks! :)

**Comment by s-a** [comment]
Ty for your feedback :+1:

**Comment by mik01aj** [comment]
FYI: now I know why `process.argv` was different when I checked it in `node debug`. It was in the debugger context. To enter the script conext, I need to use the `repl` command.
