### ISSUE TITLE
Meteor Task Force

### ISSUE THREAD

**Issue by s-a** [s-a/iron-node#38]
I use https://github.com/s-a/electron-recompile to compile native modules against current electron version.

So far it fails for the following modules within electron
- [x] sqlite3
- [x] ws
- [x] bcrypt (https://github.com/ncb000gt/node.bcrypt.js.git)

Further we need 
- [x] an alias to call `ironNode` instead of `node` for meteor command. (see: https://github.com/s-a/iron-node/blob/master/docs/METEOR.md#create-an-alias-for-meteor-as-iron-meteor)   
- [ ] fix ERR_EMPTY_RESPONSE
- [ ] identify and fix main process exception

Current status is described here : https://github.com/s-a/iron-node/blob/master/docs/METEOR.md

ref: #1

**Comment by s-a** [comment]
So far I could not get this solution work https://github.com/mapbox/node-sqlite3/issues/357

**Comment by s-a** [comment]
Next one :/

![image](https://cloud.githubusercontent.com/assets/1270662/9151392/6c4dea6c-3e01-11e5-8856-4d16aacdefb9.png)

**Comment by s-a** [comment]
![image](https://cloud.githubusercontent.com/assets/1270662/9209987/d516caf8-4079-11e5-8ea6-f844ac08269d.png)
Can not identify why it tries to load wrong binary.

**Comment by s-a** [comment]
If I replace the original binary with the new compiled one. It starts but unfortunately `http://localhost:3000/` returns `ERR_EMPTY_RESPONSE` without any exception.

**Comment by s-a** [comment]
Error: Cannot find module 'kexec'

**Comment by zvictor** [comment]
+1

**Comment by s-a** [comment]
still no help in sight :cry: I will close this issue until there is more interest.
