### ISSUE TITLE
fails on freeBSD

### ISSUE THREAD

**Issue by chadams** [s-a/iron-node#41]
> > > > npm install iron-node -g
> > > > |
> > > > electron-prebuilt@0.30.2 postinstall /usr/local/lib/node_modules/iron-node/node_modules/electron-prebuilt
> > > > node install.js

/usr/local/lib/node_modules/iron-node/node_modules/electron-prebuilt/install.js:24
if (!paths[platform]) throw new Error('Unknown platform: ' + platform)
                            ^
Error: Unknown platform: freebsd
    at Object.<anonymous> (/usr/local/lib/node_modules/iron-node/node_modules/electron-prebuilt/install.js:24:29)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! FreeBSD 10.1-RELEASE-p10
npm ERR! argv "node" "/usr/local/bin/npm" "install" "iron-node" "-g"
npm ERR! node v0.12.6
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.30.2 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-prebuilt@0.30.2 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by s-a** [comment]
Seems that freeBSD is not a Linux system sorry .
