### ISSUE TITLE
Debugger crash when script call process.exit()

### ISSUE THREAD

**Issue by mik01aj** [s-a/iron-node#45]
![screenshot 2015-08-10 15 48 34](https://cloud.githubusercontent.com/assets/3027415/9172973/519c1834-3f77-11e5-8314-def96897df8e.png)

This problem happens only when I'm running the script using `iron-node` and not when running the script using `node` or `node debug`. To be more precise: normally the script runs my `jasmine` test suite and exits. In `iron-node` is crashes _before_ running the tests.

**Comment by s-a** [comment]
Can you setup a simplified project to reproduce the error and create a repo at github? I d like to inspect this.  
Never Seen this before. Looks like a crash in chromium.

**Comment by s-a** [comment]
Are you spawning processes there? Maybe there are more infos in your terminal console log.

**Comment by mik01aj** [comment]
I created a small example: https://gist.github.com/mik01aj/873aa20f73716f626738

**Comment by s-a** [comment]
Thanks. You are running `iron-node suite.js` right? I will test this this evening

**Comment by mik01aj** [comment]
Yes.

**Comment by s-a** [comment]
OK.  
I was able to run the test suite.
![image](https://cloud.githubusercontent.com/assets/1270662/9176139/e254f398-3f89-11e5-9dcf-7785198661bd.png)

And I was able to debug the test suite.
![image](https://cloud.githubusercontent.com/assets/1270662/9176205/65c788f8-3f8a-11e5-913e-1b2f525bff90.png)

Jasmine calls `process.exit` which seems to cause a crash.
![image](https://cloud.githubusercontent.com/assets/1270662/9176235/8e0e8d16-3f8a-11e5-8c87-76b647be3ddb.png)

This hot fixes the issue.

``` javascript
process.exit = function() {}
```

Well this should impact other Libraries too so I need to overwrite `process.exit`and output exitcode to console.

**Comment by s-a** [comment]
Can you confirm that ? I updated your gist at https://gist.github.com/s-a/aaec29ad03cd7138ca8a#file-suite-js-L10

**Comment by s-a** [comment]
Regarding the strange console log I created a ticket at https://github.com/atom/electron/issues/2390.
We should change the issue title because there is nothing you can debug there :smile_cat:

**Comment by s-a** [comment]
In case of a script calls `process.exit()` you will see now a toaster as notification. This is much more fun :smiley: 

![image](https://cloud.githubusercontent.com/assets/1270662/9183166/f1078f08-3fad-11e5-90b6-a7c0b167c546.png)

**Comment by mik01aj** [comment]
Nice!

I have one more idea: maybe `system.exit` should be mocked with `function () { debugger; }`?

**Comment by s-a** [comment]
I think that's something users should decide for themselves. For some people it could be irritating. You can create packages very easy to implement your desired behavior. 

An example package is here 
https://github.com/s-a/iron-node-zerodarkmatrix-theme/blob/master/index.js. I would love to See various mutations of addons at the [package channel](https://www.npmjs.com/browse/keyword/iron-node).

**Comment by mik01aj** [comment]
How about this example?

```
setTimeout(function () { process.exit(); }, 1000);
setTimeout(function () { console.log('You will never know what I wanted to tell you'); }, 1001);
```

Will the message show up in `iron-node`? I think it will, and imho it shouldn't.

**Comment by s-a** [comment]
Yes it is a little bit weird. Would be nice to find a way to stop script execution if exit was called which is far from trivial. Seems you found a limitation here.

**Comment by mik01aj** [comment]
When you put a breakpoint there, it becomes trivial :) And you can put the real `process.exit` after it so that these strange situations will not happen.

A breakpoint at exit is very useful imho, because then I am able to inspect whole application state at exit. Think about a command/line script. It can have `process.exit()` on the end or not, it's roughly equivalent (minus waiting for any pending calls from `setTimeout`, `setInterval`, `process.nextTick`, `Promise`s or similar async mechanisms). I think that they should be "roughly equivalent" in the debugger as well, so that in both these cases (I mean a. scripts exititing explicitly using `proces.exit` and b. scripts exiting implicitly by finishing executing the main script and emptying the event loop):
1. the process behaves the same both in normal runtime and in debugger
2. it is easy to debug post-mortem state of the process.

**Comment by s-a** [comment]
We can not avoid the situation. process.exit will cause a crash because everything is based on node. Anything beyond process.exit will exit the GUI application. 
So far there is no way to detect script finished especially pending async methods done events.

**Comment by s-a** [comment]
@mik01aj check out https://github.com/s-a/iron-node-process-exit-break

**Comment by mik01aj** [comment]
It works great! Thanks! :)

**Comment by mik01aj** [comment]
I owe you a beer when I come to Hamburg!

**Comment by s-a** [comment]
:+1: :smile:
