### ISSUE TITLE
value of require.main

### ISSUE THREAD

**Issue by jsen-** [s-a/iron-node#48]
I just realized, that `require.main.filename` points to `<iron-node install dir>/iron-node/app/index.html`
I think it would be beneficial, if `require.main` contained the module loaded by iron-node, instead of iron-node itself.

I don't currently have any use case for this, so please take this just as a suggestion.
I'm pretty sure there are npm modules that rely on the suggested behavior, though.
Somewhat similar to #36.

_Edit:_ the same applies to `process.mainModule`

**Comment by s-a** [comment]
This was already reported at #34  
@mik01aj this might be interesting for you too. 

I just published a module at https://github.com/s-a/fake-require-main. Please contribute there. I personal do not use this so feel free to make this module fit your needs :+1:

**Comment by mik01aj** [comment]
@s-a you didn't account for `process.mainModule`. Looks like this one should be faked too.

**Comment by s-a** [comment]
:+1:  fixed at 1.0.2
