### ISSUE TITLE
How to debug Mocha tests?

### ISSUE THREAD

**Issue by MarkHerhold** [s-a/iron-node#51]
I cannot get iron-node to work with mocha. I have seen and read the page on ["How to debug other Node.js command line applications like a Grunt task?"](https://github.com/s-a/iron-node/blob/master/docs/DEBUG-NODEJS-COMMANDLINE-APPS.md) but that did not help.

I am able to debug things running in mocha just fine with node-inspector using:

``` shell
node-debug ./node_modules/mocha/bin/_mocha ./spec/mytest.spec.js
```

I have tried the same thing with iron-node along with passing in different arguments.

This works, but the tests all run and don't trigger the debugger.

``` shell
iron-node ./node_modules/mocha/bin/_mocha -- ./spec/mytest.spec.js
```

I am using the latest version of `iron-node` and `mocha`.
Environment: iojs 3.2.0, Ubuntu 15

**Comment by s-a** [comment]
Have you tried the keyword `debugger;`? There is also a doc.https://github.com/s-a/iron-node/blob/master/docs/MASTER-THE-BREAKPOINTS.md which might be interesting.

**Comment by MarkHerhold** [comment]
Sorry, yes I have tried the `debugger;` statement. I am not sure the source even gets loaded so I don't think I can set a breakpoint.

**Comment by s-a** [comment]
Hmm, yes mocha spawns another process where it does not work anymore.
![image](https://cloud.githubusercontent.com/assets/1270662/9572844/158e0fac-4fb5-11e5-9867-b11525e128fa.png)

I am not sure why people decide to use such a strategy. However to make it work we need to create an alias and change the call to `iron-node` instead of `node`

## alias for shell (on windows):

``` bash
# locate 
$ where mocha;
# --> C:\Users\Stephan\AppData\Roaming\npm\mocha.cmd
```

### alias file one:

``` bash
$ cp c:\Users\Stephan\AppData\Roaming\npm\mocha.cmd c:\Users\Stephan\AppData\Roaming\npm\iron-mocha.cmd;
```

#### edit iron-mocha.cmd

``` bash
:: Created by npm, please don't edit manually.
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\node_modules\mocha\bin\iron-mocha" %*
) ELSE (
  node  "%~dp0\node_modules\mocha\bin\iron-mocha" %*
)
```

### alias file two:

``` bash
$ cp c:\Users\Stephan\AppData\Roaming\npm\node_modules\mocha\bin\mocha c:\Users\Stephan\AppData\Roaming\npm\node_modules\mocha\bin\iron-mocha;
```

#### edit iron-mocha: and add `process.argv[0] = "iron-node.cmd";`

``` javascript
# c:\Users\Stephan\AppData\Roaming\npm\node_modules\mocha\bin\iron-mocha:
#!/usr/bin/env node

/**
 * This tiny wrapper file checks for known node flags and appends them
 * when found, before invoking the "real" _mocha(1) executable.
 */

var spawn = require('child_process').spawn
  , args = [ __dirname + '/_mocha' ];

process.argv.slice(2).forEach(function (arg) {
  switch (arg) {
    case '-d':
      args.unshift('--debug');
      break;
    case 'debug':
    case '--debug':
    case '--debug-brk':
      args.unshift(arg);
      break;
    case '-gc':
    case '--expose-gc':
      args.unshift('--expose-gc');
      break;
    case '--gc-global':
    case '--harmony':
    case '--harmony-proxies':
    case '--harmony-collections':
      args.unshift(arg);
      break;
    default:
      if (0 == arg.indexOf('--trace')) args.unshift(arg);
      else args.push(arg);
      break;
  }
});

process.argv[0] = "iron-node.cmd";
var proc = spawn(process.argv[0], args, { customFds: [0,1,2] });
proc.on('exit', function (code, signal) {
  process.on('exit', function(){
    if (signal) {
      process.kill(process.pid, signal);
    } else {
      process.exit(code);
    }
  });
});
```

### done

``` bash
$ cd your-projectfolder;
$ iron-mocha; # instead of mocha
```

![image](https://cloud.githubusercontent.com/assets/1270662/9572923/eb1d1672-4fb5-11e5-8232-9d104bbb4bd6.png)

**Comment by s-a** [comment]
OSOBLETE! Thanks to @michael-brade https://github.com/s-a/iron-node/issues/73#issuecomment-170208315 we have now a very smarter way to debug Mocha!  

Please refer to https://github.com/s-a/iron-node/blob/master/docs/DEBUG-NODEJS-COMMANDLINE-APPS.md for forthcoming updates.

**Comment by UriLucioWald** [comment]
Hi,
Using Windows 10 wtih Mocha I Followed the instruction above and created the files aliases , but when executing the `iron-mocha` it will do exactly like executing `mocha` and won't stop in the debugger point.
Using the latest `iron-mocha` version  `mocha 2.4.5`
The 2 alias file looks a bit different 
`#!/usr/bin/env node

/**
 * This tiny wrapper file checks for known node flags and appends them
 * when found, before invoking the "real" _mocha(1) executable.
 */

var spawn = require('child_process').spawn,
  path = require('path'),
  fs = require('fs'),
  args = [path.join(__dirname, '_mocha')];


process.argv.slice(2).forEach(function(arg){
  var flag = arg.split('=')[0];

  switch (flag) {
    case '-d':
      args.unshift('--debug');
      args.push('--no-timeouts');
      break;
    case 'debug':
    case '--debug':
    case '--debug-brk':
      args.unshift(arg);
      args.push('--no-timeouts');
      break;
    case '-gc':
    case '--expose-gc':
      args.unshift('--expose-gc');
      break;
    case '--gc-global':
    case '--es_staging':
    case '--no-deprecation':
    case '--prof':
    case '--throw-deprecation':
    case '--trace-deprecation':
    case '--allow-natives-syntax':
      args.unshift(arg);
      break;
    default:
      if (0 == arg.indexOf('--harmony')) args.unshift(arg);
      else if (0 == arg.indexOf('--trace')) args.unshift(arg);
      else if (0 == arg.indexOf('--max-old-space-size')) args.unshift(arg);
      else args.push(arg);
      break;
  }
});

<b>process.argv[0] = "iron-node.cmd"; </b>
var proc = spawn(process.execPath, args, { stdio: 'inherit' });
proc.on('exit', function (code, signal) {
  process.on('exit', function(){
    if (signal) {
      process.kill(process.pid, signal);
    } else {
      process.exit(code);
    }
  });
});

// terminate children.
process.on('SIGINT', function () {
  proc.kill('SIGINT'); // calls runner.abort()
  proc.kill('SIGTERM'); // if that didn't work, we're probably in an infinite loop, so make it die.
});
`
