### ISSUE TITLE
No log output via visionmedia/debug

### ISSUE THREAD

**Issue by jonaswindey** [s-a/iron-node#52]
Edit:

simple example
`npm i --save debug`

test.js

```
process.env.DEBUG = 'dev'
var debug = require('debug')

console.log('test')
debug('dev')('test')
```

run it with `node test` and compare it to `iron-node test`

You will see there is no output in the second case.

**Comment by s-a** [comment]
I do not know debug lib. Does it work without babel? You can configure es6 features and dont need transpiling https://github.com/s-a/iron-node/blob/master/docs/CONFIGURATION.md#v8-flags.
You could set a break point and debug what is going on at `debug('init')('starting API');`

**Comment by jonaswindey** [comment]
Yes without babel it works. And I think that's where the problems come from.

My application uses es6/es7 features (async, await, module imports etc) and I would love to debug it with iron-node but it gives me very strange errors. I don't think there are v8-flags for that, which is why I transpile with babel.

Does iron-node support sourcemaps?

**Comment by jonaswindey** [comment]
Updated my example above. Apparently it has nothing to do with babel.

**Comment by s-a** [comment]
The v8 engine supports any official es6 feature. Since you are not using experimental stuff it might be more stable to debug without babel.
Never tried source maps but it should work as described at [https://developer.chrome.com/devtools/docs/javascript-debugging#using-source maps](https://developer.chrome.com/devtools/docs/javascript-debugging#using-source maps)

If you do not see any log output it definitely belogs to your debug methods. as you mentioned `console.log('test') // this is called` works.

Have you debuged your log method?

**Comment by jonaswindey** [comment]
> The v8 engine supports any official es6 feature. Since you are not using experimental stuff it might be more stable to debug without babel.

True, except for module imports/exports. But the sourcemaps work great so that's covered.

About the logging, I think I found the problem. Even though we're running in the browser, the logger still thinks it's a node environment, and I guess it's writing it to the stdout or another stream instead of the console.log.
https://github.com/visionmedia/debug/blob/master/example/stdout.js

I guess mongoose does the same.
It would be nice though if iron-node could bind the stdout to console.log, that way it is compatible with all logging systems.

**Comment by s-a** [comment]
Just wanted to write you in #53 that iron-node is a hybrid environment while all scripts run always in a terminal console context. I dont know maybe you can include a browser version of debug.

**Comment by s-a** [comment]
> It would be nice though if iron-node could bind the stdout to console.log, that way it is compatible with all logging systems.

You can easy write your own Plugins for ironNode like this one. 
https://github.com/s-a/iron-node-process-exit-break/blob/master/index.js. Let me know if you created something awesome :smiley_cat:

**Comment by jonaswindey** [comment]
Yep, apparently it's possible: https://github.com/visionmedia/debug/blob/master/example/stdout.js
Basically you just bind debug.log to console.log

I'll take a look at the plugins system. Thanks for the help!

**Comment by jonaswindey** [comment]
Still, I think adding this code in iron-node on startup would help more users because debug is used by a lot of people. 

Do you agree?

This is the line to add:

`debug.log = console.log.bind(console);`

**Comment by s-a** [comment]
We can do this only if debug was required. I suggest to write a simple package or extend the debug library directly. Maybe they accept a PR. It would make sense to discuss this behavior with the creators of debug because it impacts the electron environment.
