### ISSUE TITLE
Debug ES6 via Babel preprocessor ?

### ISSUE THREAD

**Issue by StyMaar** [s-a/iron-node#54]
Is there a way we can preprocess ES6 code with Babel before running it with Iron node ?

**Comment by s-a** [comment]
This should work without problems. Do you get errors?

**Comment by StyMaar** [comment]
This is not that I have errors, but I have just no clue how to do it. I usually run my ES6 code using babel-node directly. If I run `iron-node myES6Code.js` it obviously doesn't work because many ES6 features I need aren't supported yet. 
I tried  `babel myES6Code.js --source-maps inline | iron-node` but it doesn't work as iron-node is not POSIX (it does not read input from stdin, but need a file path). Obviously I can build my ES6 file with babel and source-maps into a temporary file and then open iron-node on this file, but that's quite annoying. 
It would be nice if iron-node had a way to declare a pre-processor, a little bit like mocha does it : 
`mocha --compilers js:babel/register myTestFile`.
If there is such a behavior I haven't find it documented. If not it would be a great addition to your already great debugger.

**Comment by s-a** [comment]
You can config es 6 features as described at https://github.com/s-a/iron-node/blob/master/docs/CONFIGURATION.md#v8-flags. So babel might not be needed. iron Node supports source maps as described at https://github.com/s-a/iron-node/issues/52#issuecomment-137961030

@jonaswindey is using babel. May he can help out because he have more experience about this topic than me. In generell you could write a simple bash precompile your stack and exec ironNode.

**Comment by nickytonline** [comment]
@StyMaar set your sourcemaps to `both` instead of `inline`. I forget where I found that, but this seems to be the only way to get Babel source maps to work with node-inspector or iron-node.

**Comment by jonaswindey** [comment]
Just create an entry point with 2 lines: 
`require('babel/register')({stage: 0})` 
from that on, just require your main app entry point
`require('./index')`

That will give you es6/es7 with debugging functionalities. Don't forget to put your breakpoint in the file:// list of files, not in the local workspace files.

**Comment by vamsiampolu** [comment]
Thank you @jonaswindey , I can confirm that this worked, I created a new entry point for the app called `debug.js` and placed the two lines of code there.

**Comment by ericelliott** [comment]
Using the `debug.js` technique which mostly works, but now my app is ignoring the `NODE_PATH` setting, so imports are failing.

**Comment by s-a** [comment]
If it is possible to set `NODE_PATH` programmatically we could add a setup for it to [.iron-node.js](https://github.com/s-a/iron-node/blob/master/.iron-node.js).  @jonaswindey do you have already a solution for this problem? @ericelliott can you provide a simple reproducable example at github?

**Comment by s-a** [comment]
@ericelliott can you try to call this module within your code to test if we could solve the issue this way? https://www.npmjs.com/package/enforce-node-path

**Comment by ericelliott** [comment]
The `NODE_PATH` environment variable is set correctly. `enforce-node-path` seems to do nothing but throw an error if it doesn't match.

What I'm saying is that `NODE_PATH` is set as expected, but it seems to be ignored when I do this:

``` sh
    "debug:unit": "NODE_PATH=source iron-node source/test/unit/debug.js",
```

This works fine:

``` sh
    "test:unit": "NODE_PATH=source babel-node source/test/unit/index.js",
```

`debug.js` looks like this:

``` js
require('babel-core/register');
require('./index.js');
```

As you can see, the test directory containing `debug.js` is inside the `source` directory.

**Comment by s-a** [comment]
OK . Sorry... Seems environment variables are not accessible by spawned electron instance. I think this one should be adressed to a new issue.

**Comment by ericelliott** [comment]
See #98

**Comment by stoplion** [comment]
This does not work if using imports
