### ISSUE TITLE
Breakpoints works only in one version of a file

### ISSUE THREAD

**Issue by int0h** [s-a/iron-node#55]
Hello! Firstly, I'd like to say thank you, because I like your project a lot.

But I've faced a problem:
There are 2 version of file accessible by ctrl+p. One is in left tree view (with path like: proj/js/file.js) and another (with full path and no domain: D:\proj\js\file.js). And I cannot realize how to set a breakpoint in the first case. Basically I can set it, but it doesn't work. In second case (full path versions) it works fine though.

I've read readme a few times, and I still cannot solve it :( 
P.s. 
Is it possible to hide debugger sources from the tree?

**Comment by s-a** [comment]
You do not need a breakpoint for files without a domain.  This behavior is described at https://github.com/s-a/iron-node/blob/master/docs/MASTER-THE-BREAKPOINTS.md. you can disable it as described at https://github.com/s-a/iron-node/blob/master/docs/MASTER-THE-BREAKPOINTS.md#if-you-are-not-planing-to-use-the-editing-features-of-devtools

Via configuration:  
https://github.com/s-a/iron-node/blob/1cf0e727afce39f0b0927037220ae3df7e8c1ebe/.iron-node.js#L9

**Comment by int0h** [comment]
I'm sorry I still cannot understand :(

When I use ["autoAddWorkSpace" : true] - I get the project which is in debug mode in the left panel and it's nice for navigation.

But there are 2 problems:

1) I cannot master a breakpoint in MY file without a domain; "You do not need a breakpoint for files without a domain" - I'm afraid I don't get it. Because I have 2 equal files of my project with different domains. But one of them doesn't react on breakpoints. Does that mean I need use only full domain files for debugging?

2) There are a lot of files which are source code of the iron-node (or electron) it self. Is there a way to remove them from "sources" tab in the inspector?

**Comment by s-a** [comment]
1. Yes. You can safely ignore the other files. `["autoAddWorkSpace" : false]` will hide them. Debugable sources are always surounded by the Node.js module scope.
2. Unfortunately no... If you find a way: pull request are always welcome :smiley_cat:

**Comment by tipdbmp** [comment]
Is it possible to get rid of the 2 versions of the same file (the first for editing and the second (with the absolute path in the name) for setting breakpoints)? This is not the case for debugging browser scripts with the chrome dev tools. There you can use the "Map to file system resource..." option and then it get's rid of the file:// "domain" thing.

Also when debugging within the browser it preserves the positions of the breakpoints after file modifications, this doesn't seem to be the case for iron-node:

The starting script:

```
    1
    2 var foo = 1;
    3 foo += 3;
    4 console.log(foo);
```

We add a breakpoint:

```
    1
    2 var foo = 1;
    3 foo += 3; // We add a breakpoint here.
    4 console.log(foo);
```

Then we insert a line before the breakpoint:

```
    1
    2 var foo = 1;
    3 foo += 2; // We added this line.
    4 foo += 3;
    5 console.log(foo);
```

And finally we refresh (Ctrl+R) but the breakpoint doesn't stay on the `foo += 3;` line instead it's on line number 3.
