### ISSUE TITLE
cannot get es6 working

### ISSUE THREAD

**Issue by weepy** [s-a/iron-node#57]
Hi there 

I've created an `.iron-node.js` file with the v8 config options like in 

https://github.com/s-a/iron-node/blob/master/.iron-node.js

However I still get the error `Unexpected token this.on("change", () => this.stylize() )`

<img width="1033" alt="screen shot 2015-10-02 at 13 08 18" src="https://cloud.githubusercontent.com/assets/820/10246169/b16ec046-6906-11e5-92d0-e7aacd2a233d.png">

Any ideas?

**Comment by weepy** [comment]
It seems as though the iron-node.js config is not getting loaded since the configuration.settings.v8 appears to be empty ?

**Comment by s-a** [comment]
You have to place the config file into the app data folder as described at https://github.com/s-a/iron-node/blob/master/docs/CONFIGURATION.md#how-to-find-the-appdata-folder
