### ISSUE TITLE
"Module version mismatch" error

### ISSUE THREAD

**Issue by remy** [s-a/iron-node#58]
This is in the console, and it's not starting the server because of it. Hopefully there's enough info in the screenshot for versions - but please let me know if you need more.

<img width="780" alt="screen shot 2015-10-08 at 14 09 48" src="https://cloud.githubusercontent.com/assets/13700/10365813/4fca5340-6dc6-11e5-8054-49279cbecfa0.png">

**Comment by s-a** [comment]
Seems you try to load native module bcrypt. Did you compiled the binaries against the current ironNode runtime version of node?

My help docs are a mess so here 's  a link.

https://github.com/s-a/iron-node/blob/master/docs/NATIVE-MODULES.md#--compile-compile-all-native-modules-in-nodejs-project
- `iron-node --compile` compile new binaries (not destructive) into a seperate subfolder.
- https://github.com/s-a/iron-node/blob/master/.iron-node.js#L8 `native+` extends require to search native modules respecting the current v8 engine version. (compiled in the step before)

**Comment by s-a** [comment]
Does this help?

**Comment by remy** [comment]
Sorry, need to check at the weekend!

**Comment by remy** [comment]
Hey, I tried today. Same problem. Here's what I ran:

``` shell
$ iron-node --compile=.
$ iron-node .
```

And I get the same error as above. I also tried with `iron-node --compile` but it just hung, so I figured it needed some pointing.

**Comment by s-a** [comment]
Hmm, do you have iron-node installed with npm? Or another package manager?
These Version DLL hell makes me crazy. I found this... Maybe it helps.
https://github.com/ncb000gt/node.bcrypt.js/issues/347 Other wise would be
cool if you could publish a reproducable sample. I d like to check this out
this weekend.

Did the compile process finished successfuly?
Am 12.10.2015 17:48 schrieb "Remy Sharp" notifications@github.com:

**Comment by s-a** [comment]
Seems like a npm update could fix it?

**Comment by remy** [comment]
It was via npm (the version that comes with 4.1.0). Compilation did finish.

**Comment by s-a** [comment]
Just tried to reproduce but I fail in a step before on Windows32 with npm install bcrypt. :disappointed: I will retry frequently

**Comment by s-a** [comment]
@remy check this https://github.com/s-a/iron-node/issues/60#issuecomment-149783292 out. I believe this can help you.

**Comment by s-a** [comment]
This works since iron-node 2.0.0

![image](https://cloud.githubusercontent.com/assets/1270662/11760870/46222916-a0ad-11e5-86b6-09961997e5b4.png)

`npm install bcrypt`
`iron-node --compile`

```
var bcrypt = require('bcrypt');


bcrypt.genSalt(10, function(err, salt) {
    bcrypt.hash('B4c0/\/', salt, function(err, hash) {
        // Store hash in your password DB. 
        debugger;
        console.log(err,hash);
    });
});
```

**Comment by gritzko** [comment]
In 2.0.2 I am getting this: `Error: Module version mismatch. Expected 47, got 46.`

``` bash
rm -rf node_modules
npm install
$ node -v
v4.2.3
$ which iron-node 
/opt/node-v4.2.3-linux-x64/bin//iron-node
$ npm -v
2.14.7
```

**Comment by gritzko** [comment]
`node_modules/electron-prebuilt/dist/libgcrypt.so.11`
Is this the suspect?
Why do you need it, in the first place?

**Comment by s-a** [comment]
I am not the creator of electron prebuilt, but have you recompiled binaries with electron --compile?

**Comment by zeezali** [comment]
@s-a   I'm having the same issue as @gritzko in **2.0.2**.

In my case the only native module that I'm using is [lwip](https://github.com/EyalAr/lwip). I've compiled **lwip** successfully using `npm install` with Node `v4.2.2` and `v5.1.1` (which I think the latest prebuilt version of Electron is using), so I don't think it has any compatibility issues with Electron's Node runtime.

I've tried `iron-node --compile` in multiple ways with no luck:

```
# 1
cd /abs/path/to/my/project
iron-node --compile=.

# 2
iron-node --compile=/abs/path/to/my/project

# 3
cd /abs/path/to/my/project
iron-node --compile ./

# 4
iron-node --compile /abs/path/to/my/project

#5
cd /abs/path/to/my/project
iron-node --compile
```

I also tried adding the `.iron-node.js` local config file with `native+: true`, but that didn't seem to make any difference.

I always get this error:

```
Error: Module version mismatch. Expected 47, got 46.
```

Going forward, I'm really excited to see what happens with the `external-node` branch you just created. Since everyone is using a different version of Node, you might be able to prevent native module issues if **iron-node** was using the same version as the local version installed on the user's machine.

**Comment by BigAB** [comment]
This problem persists at version `2.1.14`, whenever bcrypt is in node_modules.

`iron-node --compile` does not seem to change anything.

**Comment by s-a** [comment]
@BigAB you need to setup `native+:true` to tell ironNode to use recompiled modules.  
@zeezali Unfortunately contributors of those branches never reported back.

**Comment by BigAB** [comment]
Well I am not sure what I am doing wrong then.

I put a file `.iron-node.js` with the contents:

``` javascript
var path = require("path");
var settings = {
  "v8": {
    "flags" : []
  },
  "app": {
    "native+"               : true,   // DEFAULT=FALSE; extends require to search native modules respecting the current v8 engine version.
    "autoAddWorkSpace"      : false,  // DEFAULT=TRUE; disables the autoAddWorkSpace behavior.
    "openDevToolsDetached"  : true,  // DEFAULT=FALSE; opens the dev tools windows detached in an own window.
    "hideMainWindow"        : false  // DEFAULT=FALSE;  hides the main window to show dev tools only.
  }
};

module.exports = settings;

```

in `~/Library/Application\ Support/iron-node/`, and it seems to work because it respond to the `openDevToolsDetached` and `hideMainWindow` settings correctly.

I re-ran `iron-node --compile`...

But when I try on my project I still the same error:

```
Error: Module version mismatch. Expected 47, got 46.

- Error

- ATOM_SHELL_ASAR.js:159 process.module.(anonymous function) [as dlopen]
  ATOM_SHELL_ASAR.js:159:20

- ATOM_SHELL_ASAR.js:159 Object.module.(anonymous function) [as .node]
  ATOM_SHELL_ASAR.js:159:20

- require.js:56 Module.require
  [lib]/[iron-node]/app/require.js:56:25

- bindings.js:76 bindings
  [jobcosttracker]/[feathers-authentication]/[bcrypt]/[bindings]/bindings.js:7    6:44

- bcrypt.js:3 Object.<anonymous>
  [jobcosttracker]/[feathers-authentication]/[bcrypt]/bcrypt.js:3:35

- node.js:214 Object.require.extensions.(anonymous function) [as .js]
  [jobcosttracker]/[babel-core]/lib/api/register/node.js:214:7
```

Any help would be appreciated, as I really like using iron-node, but I need these modules for this project.

I am on a Mac by the way. OS X 10.11.3.

**Comment by s-a** [comment]
Can you try this without native+ option? 
https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md#the-easy-way

**Comment by BigAB** [comment]
Trying that without the native+ options gives me this message:

```
$ ./node_modules/.bin/electron-rebuild
Unable to find electron-prebuilt's version number, either install it or specify an explicit version
```

**Comment by BigAB** [comment]
Oh wow. It worked when I added the **electron-prebuilt's version number**.
Yay, now I can use iron node again.

I have no idea what just happened, but much like copy-pasta-code, I follwed the directions, invoked the magical incantations and everything works so I am happy.

**Comment by tywrr** [comment]
In my case `./node_modules/.bin/electron-rebuild -v 0.36.3` did it.

**Comment by venkatesh3007** [comment]
`iron-node --compile=<path> doesn't work`

The error is thrown for bcrypt.

my stack - 

```
node - 5.3.0
npm - 3.3.12
iron-node - 3.0.11
```
