### ISSUE TITLE
Reload program on file change

### ISSUE THREAD

**Issue by srolel** [s-a/iron-node#59]
Is it possible to achieve functionality similar to nodemon? I could, of course, use nodemon but it closes and reopens iron-node.

**Comment by s-a** [comment]
So far there is no monitoring on the road map. I fear this would result in a weird debug experience. There was already a request at https://github.com/s-a/iron-node/issues/47. I will leave this issue open. So we can see if more users find this useful.

**Comment by srolel** [comment]
I wrote a small module implements something like this. works with and agnostic to iron-node.
https://github.com/Mosho1/reacquire

I thought this would be useful to others, but let me know if you think this isn't the right place to post it.

**Comment by s-a** [comment]
This is a good place to post :+1:
