### ISSUE TITLE
OS/X node-sass on Node 4 blows up

### ISSUE THREAD

**Issue by thepian** [s-a/iron-node#61]
I got an error, even after rebuilding.

Error: The `libsass` binding was not found in /Users/Shared/Projects/ss-examples/express-4-and-js/node_modules/node-sass/vendor/darwin-x64-44/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/Users/Shared/Projects/ss-examples/express-4-and-js/node_modules/node-sass/lib/extensions.js:150:11)
    at Object.<anonymous> (/Users/Shared/Projects/ss-examples/express-4-and-js/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.requires [as require](/Users/Shared/Projects/socketstream/lib/utils/require.js:75:11)
    at module.exports (/Users/Shared/Projects/socketstream/lib/client/formatters/sass.js:8:17)error @ app.js:19emitOne @ events.js:77emit @ events.js:169window.onerror @ /usr/local/lib/node_modules/iron-node/node_modules/electron-prebuilt/dist/Electron.app/Contents/Res…:75

**Comment by thepian** [comment]
It also seems that linked modules are ignored. I need to develop with `npm link` so that's a non-starter.

**Comment by s-a** [comment]
I planed to upgrade this weekend to Node 4 but found no time so I need to shift this to next weekend. 
You can try yourself as described at https://github.com/s-a/iron-node/issues/60#issuecomment-149783292.

Regarding symlinks this should be a separate issue.

**Comment by s-a** [comment]
Have you tried iron-node --compile? You need to compile against v8 version shipped by iron Node.

**Comment by s-a** [comment]
Just tried to recompile against electron runtime environment

```
node-gyp.cmd [ 'rebuild',
  '--target=0.36.0',
  '--arch=ia32',
  '--dist-url=https://atom.io/download/atom-shell' ]
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@4.2.2 | win32 | ia32
gyp info spawn python
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\iron-node\\node_modules\\electron-    recompile\\tmp\\node-sass@3.4.2\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\iron-node\\node_modules\\electron-    recompile\\tmp\\electronGypHome\\.node-gyp\\0.36.0\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\iron-node\\node_modules\\electron-    recompile\\tmp\\electronGypHome\\.node-gyp\\0.36.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\iron-node\\node_modules\\electron-    recompile\\tmp\\node-sass@3.4.2',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Stephan\\AppData\\Roaming\\npm\\node_modules\\iron-node\\node_modules\\electron-    recompile\\tmp\\node-sass@3.4.2\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: name 'libsass_ext' is not defined while evaluating condition 'libsass_ext == "" or libsass_ext == "no"' in binding.gyp while     trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\node-gyp\lib\configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js"     "rebuild" "--target=0.36.0" "--arch=ia32" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd C:\Users\Stephan\AppData\Roaming\npm\node_modules\iron-node\node_modules\electron-recompile\tmp\node-sass@3.4.2
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

You should open a ticket at the node-sass repo. Seems there is a problem with the current connfiguration

**Comment by s-a** [comment]
Even https://github.com/electronjs/electron-rebuild/issues/42 cannot handle this :\
