### ISSUE TITLE
Folder context when working with command line tools (Gulp, Grunt, Webpack...)

### ISSUE THREAD

**Issue by shlomiassaf** [s-a/iron-node#63]
Working with webpack, directory mapping is logically correct but contextually wrong.

Running per [instructions](https://github.com/s-a/iron-node/blob/master/docs/DEBUG-NODEJS-COMMANDLINE-APPS.md) map the root folder to the location of the command line tools.

Calling iron-node with reference to the command line tool in its global location:

```
$  iron-node /C/Users/Shlomi.ASSAF/AppData/Roaming/npm/node_modules/webpack/bin/webpack
```

The mapped folder root is now:
`/C/Users/Shlomi.ASSAF/AppData/Roaming/npm/node_modules/webpack/bin/`

![image](https://cloud.githubusercontent.com/assets/5377501/11166294/8150e8ec-8b36-11e5-8839-e787f3e6deb2.png)

This is logically correct however the actual root should be the execution folder (process.cmd).

To workaround that I`v added a file (to my project's root) that just requires the command line script:

```
require("C:\\Users\\Shlomi.ASSAF\\AppData\\Roaming\\npm\\node_modules\\webpack\\bin\\webpack.js");
```

Now running `iron-node webpack` on my project's root will map to the local folder, allowing me to liveedit...
This is of course wrong in many ways and will have to be more sophisticated to work in teams...

Is it possible to add a flag that allows settings the execution folder at the root for folder mapping? or setting it manually....

**Comment by s-a** [comment]
The workspace setup is here...   https://github.com/s-a/iron-node/blob/master/app/app.js#L186
Your usecase isnt trivial. Maybe you have already a good idea to resolve this issue?

**Comment by s-a** [comment]
Please check out https://github.com/s-a/iron-node/releases/tag/v2.1.6
