### ISSUE TITLE
Remote debugging?

### ISSUE THREAD

**Issue by mark-hahn** [s-a/iron-node#64]
Is there an inherent architectural reason iron-node cannot debug remotely?  I have to do everything remotely and I'd love to try this.

**Comment by s-a** [comment]
Well I guess it would be possible, but remote debugging is not the specialty of iron-node. There are better soultions out there for this purpose. However if you are interested in this any pull request is appreciated.

**Comment by mark-hahn** [comment]
Thx for the reply.  I'll check out the source.  My experience in past projects is that making remote machines look local isn't hard.

**Comment by s-a** [comment]
I think this would be a pretty cool feature. My experience level in this topic is very low. But let me know if you need help or infos.
