### ISSUE TITLE
Issue with npm v3

### ISSUE THREAD

**Issue by cvburgess** [s-a/iron-node#65]
Trying to get iron-node set up with node 5/npm 3 and this error keeps popping up:

```
Error: ENOENT: no such file or directory, scandir '...{my-project}/node_modules/iron-node/node_modules'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:449:28)
    at PackageController.getInstalledPackages ...{my-project}/node_modules/package.js/lib/index.js:17:17)
    at PackageController.autoload (...{my-project}/node_modules/package.js/lib/index.js:69:8)
    at boot (file:///...{my-project}/node_modules/iron-node/app/app.js:155:20)
    at file:///...{my-project}/node_modules/iron-node/app/app.js:199:1
```

Im assuming this has to do with the flat file structure of NPM 3 but i have no idea

**Comment by maxmx** [comment]
+1 happening here as well.

**Comment by s-a** [comment]
You could try to create this folder to workaround...  https://github.com/s-a/iron-node/blob/master/app/app.js#L134

**Comment by s-a** [comment]
Let us know if this works

**Comment by maxmx** [comment]
Workaround works, I can add that folder creation in the post install of our project, would be nice if that worked out of the box though.

**Comment by s-a** [comment]
:+1:  I will fix it in next release.
