### ISSUE TITLE
Iron-node uses a different version of Node than I use locally

### ISSUE THREAD

**Issue by mik01aj** [s-a/iron-node#67]
I have Node 4.2.0 installed with `nvm`. When I run my scripts using `node` or `npm run`, they use Node 4.2 (my app requires this specific version). However, when I run it using iron-node, I see this:

![screenshot 2015-12-10 10 42 16](https://cloud.githubusercontent.com/assets/3027415/11712100/2f7cf5de-9f2b-11e5-89b2-38c27da56d35.png)

(Possibly related to https://github.com/s-a/iron-node/issues/62.)

**Comment by s-a** [comment]
Iron Node ships its own node. I will upgrade Node version this weekend maybe your problem is fixed then.

**Comment by s-a** [comment]
Repo is already up-to-date with that via latest PR. You could try to clone and npm install -g from repo root folder.

**Comment by s-a** [comment]
Sorry the node version is compiled within iron-node eg electron. So it is not pssible to target another version of node.js. You could try iron-node 2.0.0 there is node 5 under the hood.
