### ISSUE TITLE
Error installing the package after upgrading to node v. 5.2.0

### ISSUE THREAD

**Issue by ghost** [s-a/iron-node#68]
Error Message: Make sure you have the last version! It's already the last version.

**Comment by s-a** [comment]
Can you send a screenshot pls?

**Comment by ghost** [comment]
![screenshot from 2015-12-22 19-21-06](https://cloud.githubusercontent.com/assets/7091543/11961427/32d879a0-a8e1-11e5-89ef-4d40ba9f688f.png)

**Comment by s-a** [comment]
You should try this with root permission.

**Comment by ghost** [comment]
I'm in the root already as you can see
root@localhost

**Comment by s-a** [comment]
Hmm, but this is a permission error. This impacts only ironNode on your system?

**Comment by s-a** [comment]
You could also try 
http://stackoverflow.com/questions/tagged/iron-node.
