### ISSUE TITLE
Debug CoffeeScript

### ISSUE THREAD

**Issue by DaQuirm** [s-a/iron-node#69]
Is it possible to debug CoffeeScript (run with `coffee` instead of `node`) or other compiled-to-JS languages? I tried running the `coffee` "binary" the same way as described for Grunt/Mocha but it didn't work for me.

It failed in `app.js` on

``` js
var config = new require("./config.js")(remote.process.argv);
```

with this exception:

Error: Cannot find module 'app' at Function.Module._resolveFilename (module.js:338:15) at Function.Module._load (module.js:289:25) at Module.require (module.js:366:17) at require (module.js:385:17) at Object.<anonymous> (/usr/local/lib/node_modules/iron-node/app/config.js:7:8) at Module._compile (module.js:425:26) at Object.Module._extensions..js (module.js:432:10) at Module.load (module.js:356:32) at Function.Module._load (module.js:313:12) at Module.require (module.js:366:17)

**Comment by s-a** [comment]
Well, some people here using babel as pr-processor. I doubt its possible to debug coffee script directly. I suggest to create a simple startup script to call coffe from within Node. Then it should be possible to debug the compiled result.

**Comment by DaQuirm** [comment]
Thank you, I'll give it a try.

**Comment by franciscolourenco** [comment]
Would be great if iron-node automatically handled the process when .coffee files are detected: `iron-node app.coffee`

**Comment by s-a** [comment]
ref #78
