### ISSUE TITLE
Not working on Ubuntu 14.04 node 0.12.6

### ISSUE THREAD

**Issue by naholyr** [s-a/iron-node#7]
Note sure if I misunderstood the point of the project, but it's not like it's debugging my node server :(

Node code:

``` js
var http = require('http')

var server = http.createServer(function (req, res) {
  res.end('Hello')
})

server.listen(8080)
```

How I run Iron Node:

``` sh
iron-node httpserver.js
```

What I get:

![selection_187](https://cloud.githubusercontent.com/assets/214067/8767688/f2a525a0-2e64-11e5-805f-eb459d78bfc9.png)

The server seems stopped before running (like with `--debug-brk`) which is OK I guess, but there is no link between my server and the Iron Node UI.

**Comment by s-a** [comment]
I ve tested this with express.js which worked well.  Is this your whole code? You need definitely the keyword `debugger` at code line where you want to stop. Otherwise your server should run and available at port 8080.  Anyway the window looks a little bit weird. I will try this tomorrow on linux.

**Comment by s-a** [comment]
Thanks for reporting this! Just fixed the problem on Ubuntu. After testing this on windows I will publish v1.0.6 
![image](https://cloud.githubusercontent.com/assets/1270662/8771525/ff7b3cb6-2ec2-11e5-9f8c-8cb90831c29c.png)

**Comment by s-a** [comment]
@naholyr Just published a new version at NPM. Please let us know if this works for you.

**Comment by naholyr** [comment]
Working, very well done!

Good approach, faster than node-inspector, I'll dig into the code ASAP to contribute if needed :) Thanks for the good work.

The next big step would be a little less visible left frame :P or even make it customizable project-wide (I'll open an issue about that)
