### ISSUE TITLE
Hide side menu

### ISSUE THREAD

**Issue by DylanPiercey** [s-a/iron-node#70]
Is it possible to hide the left side menu entirely with iron node? I'm somewhat use to node-inspector which only shows the console itself.

Alternatively it would be cool if it was possible to say which web page should show.

**Comment by s-a** [comment]
To show another page simply call `window.location.href = "http://www.example.com";` anywhere in your startup script. Keep in mind that this has side effects for the GUI

**Comment by DylanPiercey** [comment]
This seems to cause iron-node to crash in `v2.0.3`. (Errors and screen goes white.)

**Comment by s-a** [comment]
checkout https://github.com/s-a/iron-node/blob/10ecde9d6c5c96f383998e7c4a895f8e70b231b1/.iron-node.js#L10 for ironNode v2.1.4

**Comment by george-norris-salesforce** [comment]
Is it possible to hide it though?
