### ISSUE TITLE
Add some kind of getting started doc?

### ISSUE THREAD

**Issue by mikemaccana** [s-a/iron-node#72]
https://s-a.github.io/iron-node/ has a link called Documentation but it just goes to a directory listing with no README.md. Maybe add a README with whatever else one needs to get iron node running?

**Comment by s-a** [comment]
You do not need anything more to run ironNode expect `npm install iron-node -g`. What do you mean in detail?

**Comment by mikemaccana** [comment]
Looking around, 'Documentation' should point to https://github.com/s-a/iron-node/blob/master/README.md (which actually shows how to use iron-node) rather than https://github.com/s-a/iron-node/tree/master/docs (which is a directory listing)
