### ISSUE TITLE
How to use with mocha on Linux?

### ISSUE THREAD

**Issue by michael-brade** [s-a/iron-node#73]
I have seen your post about iron-node with mocha on Windows. However, I am not sure how to map that; my attempts have failed so far. I don't have that first file `C:\Users\Stephan\AppData\Roaming\npm\mocha.cmd`. I have `/usr/local/bin/mocha`, a link to `../lib/node_modules/mocha/bin/mocha` with the content you have in file two. Adding the 

```
process.argv[0] = "iron-node.cmd";
```

is the problem - why that on Windows, i.e., what was the intention? And what should I do on linux instead?

I tried to change `node` to `iron-node` in `_mocha`, but that leads to

```
Error: Cannot find module './options'(…)
    error @ app.js:19
    emitOne @ events.js:77
    emit @ events.js:169
    window.onerror @ /usr/local/lib/node_modules/iron-node/node_modules/electron-prebuilt/dist/resources/atom.asar/rende…:76
```

So... any hints? :)

**Comment by s-a** [comment]
`process.argv[0] = "iron-node.cmd";` will spawn an iron-node instance instead of node. `.cmd` is windows specific. Simply write `process.argv[0] = "iron-node";` instead.

**Comment by michael-brade** [comment]
Wow, I made it! Two things were the problem on Linux:
- iron-mocha in `/usr/local/bin/iron-mocha` MUST be a link to `/usr/local/lib/node_modules/mocha/bin/iron-mocha`, the latter being a copy of `mocha` in the same directory. That keeps the correct paths and fixes the `./options` module not found error.
- setting `argv[0]` doesn't do anything on linux. Instead, I hard-coded it in iron-mocha. Here's the end of that file:

``` js
[...]

// used to be: process.execPath
var proc = spawn('/usr/local/bin/iron-node', args, { stdio: 'inherit' });
proc.on('exit', function (code, signal) {
  process.on('exit', function(){
    if (signal) {
      process.kill(process.pid, signal);
    } else {
      process.exit(code);
    }
  });
});
```

Maybe you can add that to the README?

**Comment by michael-brade** [comment]
And now I have to add: thanks so much for iron-node! Finally debugging is fun again :)

**Comment by michael-brade** [comment]
Ok, one more comment, and this one is almost embarrassing: now that I have understood how it works, I realized that the original `_mocha` is all we need! Instead of doing any copying/editing, just do this:

``` sh
iron-node node_modules/.bin/_mocha ...  # or: /usr/local/bin/_mocha
```

instead of

```
mocha ...
```

Duh.

**Comment by s-a** [comment]
@michael-brade thanks for figuring this out. :+1:  
I just published https://github.com/s-a/iron-mod to make those things easier... Do you like to contribute there?

**Comment by s-a** [comment]
_mocha is pretty cool :smile:

**Comment by michael-brade** [comment]
sure. Though it seems like a lot of code for such a simple task... when I woke up this morning, the first thing I thought was exactly what you did in `.../patchers/mocha.js`. But, as I said, then I realized that this is the exact purpose of the `_mocha` "binary". 

And you'd have to update the iron-mocha potentially every time the mocha version gets bumped. That is annoying. You'd also have to copy `options.js` or figure out the full path to it (by following the link from `<whatever>/bin/mocha`). Really, sounds like too much work to me. All that just to be able to do `iron-mocha` instead of `iron-node node_modules/.bin/_mocha`.

**Comment by s-a** [comment]
Indeed. lets use _mocha there. But there some more commandline apps like grunt gulp etc out there.

**Comment by michael-brade** [comment]
You know what? I have an even better idea! (possibly :smile:) Ship a script called `iron-mocha` with `iron-node` that basically has the following content:

```
#!/bin/sh
path=$(readlink -f $(which mocha))
path=${path/\/bin\/mocha/\/bin\/_mocha}
iron-node $path $@
```

That's it. Maybe use node instead of `sh` to make it work on Windows. There should be `which` and `readlink` available in Node.

**Comment by michael-brade** [comment]
True about grunt and gulp. I would imagine this being even harder, though. Think of all those processes being spawned... ugh.

**Comment by s-a** [comment]
Hmm this iron mocha script is realy a cool idea! 
I checked some commandline apps out. Not all of them will spawn. But may be there are simillar mechanisms available like _mocha. Or it could be a way to submit issues to the different repos. Maybe the creators are willing to support such a way.

**Comment by michael-brade** [comment]
Sounds good. One more improvement: no need for `readlink -f`, `_mocha` is installed alongside `mocha`. Cool. Here is a script I actually tested:

```
#!/bin/sh
path="$(which mocha)"
iron-node "${path%mocha}_mocha" "$@"
```

Pretty simple, huh? :smiley:

**Comment by s-a** [comment]
This is amazin simple...

just palced this into my package.json script block...

```
"scripts": {
    "debug-mocha": "iron-node node_modules/mocha/bin/_mocha",
},
```

then we can use `npm run debug-mocha` :+1:

**Comment by s-a** [comment]
same with grunt :smile: 

```
"debug-mocha": "iron-node node_modules/mocha/bin/_mocha",
"debug-grunt": "iron-node node_modules/grunt-cli/bin/grunt build",
```

**Comment by s-a** [comment]
@michael-brade 
can you clarify that this works on linux? I suggest to publish a "scripts" list for package.json at https://github.com/s-a/iron-node/blob/master/docs/DEBUG-NODEJS-COMMANDLINE-APPS.md . People could copy paste script commands from there. What do you think?

**Comment by michael-brade** [comment]
@s-a oh yes, yes, it absolutely works! :) That is how I did it in my package.json as well, I just called it 'iron-mocha'. And I agree, collecting the scripts in one place is great! Additonally, I would still add the most common ones to iron-node itself and install them alongside iron-node, maybe iron-mocha for now. Or what do you think? In the end it doesn't really matter, especially if people do some custom `npm run test-whatever` already. It would just be a little treat :)

**Comment by s-a** [comment]
I d like to learn how mocha installes multiple bin files. Additionally we need to diference and let the user the choice between global and local installation for example of mocha. I personally always prefer local installations. For me its enough to have a collection at the docs, but you are welcome to contribute :)
However, maybe  we are well advised to let the user configure this manually.

**Comment by michael-brade** [comment]
I completely agree, I'm the same. Installing several bins is straightforward: just declare them under "bin" in a map. Global and local installations are handled automatically, if you npm i -g then it would end up globally, and if you have a local package dependency, the bins would end up locally under `node_modules/.bin`, too. It's just that you cannot configure manually _which_ bins to include in the installation... You'd have to create a postinstall script that asks the user, but is it worth it? I'll see what I can put together, I have way too much to do and way too little time....
