### ISSUE TITLE
Cannot read property 'on' of undefined at Toaster.init

### ISSUE THREAD

**Issue by Faleij** [s-a/iron-node#74]
``` Bash
$ systeminfo
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.10586 N/A Build 10586
$ node -v
v4.2.2
$ npm -v
2.14.7
$ npm install iron-node -g
\
> electron-prebuilt@0.36.3 postinstall C:\Program Files\nodejs\node_modules\iron-node\node_modules\electron-prebuilt
> node install.js

C:\Program Files\nodejs\iron-node -> C:\Program Files\nodejs\node_modules\iron-node\bin\run.js
iron-node@2.1.4 C:\Program Files\nodejs\node_modules\iron-node
├── open@0.0.5
├── nmp@1.0.3
├── package.js@1.1.3
├── semver@5.1.0
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── electron-toaster@2.0.1
├── markdown@0.5.0 (nopt@2.1.2)
├── electron-recompile@1.0.16 (colors@1.1.2, fs-extra@0.23.1)
└── electron-prebuilt@0.36.3 (extract-zip@1.4.1, electron-download@1.4.1)

$ iron-node
```

The last command, or any attempt at starting iron-node with any file results in the below error message and the Iron-node electron window is black with the electron debugger disconnected.
![Imgur](http://i.imgur.com/sgZL97k.png)

**Comment by s-a** [comment]
I cannot reproduce this, but planed a long time to remove my toaster module in favor of electron's notification. Could you please try https://github.com/s-a/iron-node/releases/tag/v2.1.5?

**Comment by Faleij** [comment]
2.1.5 does not solve the issue, but modifying `app/index.js` to declare `ipc` as `var ipc = require('ipc');` and `app/app.js` to declare `ipc` as `var ipc = require('ipc-renderer');` solves this issue for me.

**Comment by Faleij** [comment]
had an old version of electron installed globally that overrode the local version used in iron-node, removing it solved this issue without any modifications.
Also, @s-a thank you for your quick reply and your efforts to solve my issue.
