### ISSUE TITLE
[question] can I use iron-node to debug a sails.js app?

### ISSUE THREAD

**Issue by irobayna** [s-a/iron-node#75]
I was wondering if I can debug a sails.js application.  I have tried booting up a sails.js app using iron-node and the app runs but breakpoints don't seem to trigger.

Am I doing something wrong or is it simply that sails.js are not supported?

BTW, great project!

**Comment by s-a** [comment]
In general everything :smile: I personaly use it to debug Express.js apps. It could become tricky if you use native modules. Keep in mind that iron-node 2.1.7 have node v5.1.1 under the hood.

However it sounds sails could spawn another node instance if your breakpoints will not reach. Could you please clarify this and read https://github.com/s-a/iron-node/blob/master/docs/DEBUG-NODEJS-COMMANDLINE-APPS.md for more infos. Would be nice if you could add a sails-debug script there :+1:

**Comment by s-a** [comment]
Seems it is easy as `$ iron-node app.js;`?

![image](https://cloud.githubusercontent.com/assets/1270662/12330178/0561df24-bae4-11e5-844d-8a798c8651c0.png)

**Comment by irobayna** [comment]
@s-a  My bad, I assumed Iron-node would break on the first line and then I would be able to set break points throughout the system (similar to node-inspector)

`works perfectly`, all I had to do is to use the keyword `debugger;`

**Comment by s-a** [comment]
Hm I believe many people do not see How easy iron-node does work or How it works ... Id like to improve the docs. ... But do not know How... Any ideas? Maybe we should create some tutorial Videos.

**Comment by irobayna** [comment]
@s-a I am sorry to say that I stumbled upon this projects months ago and at first read did not quite understood the power and simplicity and it took me really until today to get this going :-(  
IMHO, This is a rocket compared to how slow and buggy `node-inspector` is.  

To help newcomers, I would suggest adding a simple comparison between `iron-node` vs. `node-inspector` so one can easily grasp the key differences.  For instance, showing how fast you can start debugging with `iron-node` seems to me should win over many fans to this project as you currently waste a lot of time with `node-inspector`

**Comment by s-a** [comment]
:+1: not easy :smile: 
I have added a getting started section to the home page.

![image](https://cloud.githubusercontent.com/assets/1270662/12376318/26b23e16-bced-11e5-9b76-4f905cbe5816.png)

Something like a comparison is available at https://github.com/s-a/iron-node/blob/master/docs/FEATURES.md.
