### ISSUE TITLE
Support for code piped through stdin

### ISSUE THREAD

**Issue by franciscolourenco** [s-a/iron-node#78]
This would allow any transpiler to be used on the fly without extra files or configuration.

Examples: 
- `babel app.es6 | node-iron`
- `coffee -p app.coffee | node-iron`
- etc...

**Comment by s-a** [comment]
Just thought about... But how we should handle Ctrl+r code reloading?

**Comment by franciscolourenco** [comment]
Not possible I guess. Other way of achieving the same is have an option to pass a command to get the code. Having the command, then you could just run the command again. 

```
iron-node --execute 'coffee -p app.coffee'
```

**Comment by s-a** [comment]
But I like this pipe idea :smile: Maybe we can access piped terminal commandline text to repeat the preprocess.

**Comment by franciscolourenco** [comment]
The place where terminal history is saved varies depending on the shell :/

**Comment by s-a** [comment]
Yes I know and it seems there is no module out there solving this...

**Comment by s-a** [comment]
I succesfuly got access to `stdin` data at 
https://github.com/s-a/iron-node/blob/e844eac23fb8a0f7f2285dab9318ab3a4fe2fc78/bin/run.js#L17

But having trouble to access `stdin` at the `main process` module.
https://github.com/s-a/iron-node/blob/e844eac23fb8a0f7f2285dab9318ab3a4fe2fc78/app/index.js#L11

I Created a test script at https://github.com/s-a/iron-node/blob/e844eac23fb8a0f7f2285dab9318ab3a4fe2fc78/package.json#L16 `pipe-test`

May be someone can help out?

**Comment by s-a** [comment]
Sorry @aristidesfl this cannot work native on Microsoft Windows. We can only ugly work around when we use a temporary file to share piped result with `electron.exe`. So far I cannot see super advantages instead of using a simple bash script. Unless there are strong requests to add piped stdin support I will not implement that.

**Comment by franciscolourenco** [comment]
It wouldn't matter how it is implemented as long as the complexity would be hidden from the user :) That way the simple "bash script" only had to be written once in node-iron in the form of pipe support.

**Comment by s-a** [comment]
I want give it a try, but should we store the tempfile in the working directory? it has an impact on later required files.

**Comment by s-a** [comment]
@aristidesfl could you please test if this works for you by installing from repo?

```
git clone https://github.com/s-a/iron-node.git
cd iron-node
npm install -g
echo var i = 0;debugger; | iron-node
```

**Comment by s-a** [comment]
This work fine for me. I will publish a new version in a few minutes.
![image](https://cloud.githubusercontent.com/assets/1270662/12562432/6f5578ea-c3a5-11e5-95f5-eed1974219b3.png)
