### ISSUE TITLE
Give love to left frame

### ISSUE THREAD

**Issue by naholyr** [s-a/iron-node#8]
I understand the importance of the left frame for your own good, but it would be even greater if it would be useful for the debugged project ;) I think the share buttons are pretty useless and could be replaced with a single link to project's homepage, whereas the donation button could be more exposed.

I also imagine very good usages for this frame (all while keeping the donation button and link to homepage). If user could inject any HTML he wants the tool could be used for very nice and various unintended situations:
- Training exercices: left frame gives the context, the goal, and user has to edit the code directly in debugger to make it work
- General instructions: tell your co-workers about project specifics that may impact the debugging session, maybe tips about dev environment…
- This could even be used to add some debugging and profiling pro-tips if nothing is specified by user

**Comment by s-a** [comment]
:+1:  I thought about some thing like this but did not found good usecases yet. Please keep in mind that this software is very young. I want to make the basic functions super stable first before adding new features.  
Anyway I like your idea. The goal should be to keep left frame functions usable offline to ensure everybody is able to develop without internet. It should also not influence command line arguments to keep usage identical to Node.js. I could imagine to work with a json config file.

**Comment by naholyr** [comment]
Yeah I was thinking about something like:
- if .iron-node.json is found use it to include content (options could be the html file and donation bar position)
- else if .iron-node.html is found, include it with default position
- else default

:+1: to keep CLI untouched, you can also use env variables to customize behaviors.

And :+1: about keeping the basement strong before building up ;) it sure is just an idea

**Comment by s-a** [comment]
Sounds cool. It should run in try catch and fall back to default behavior.

**Comment by s-a** [comment]
I am not a good designer but played a little bit around with a tiny footer at https://github.com/s-a/iron-node/tree/info-window. 
I think this is a good starting point to provide a nice large area for project' s general instructions. By default this could be README.md. 

I feel markdown syntax is the right approach for this place.

![image](https://cloud.githubusercontent.com/assets/1270662/8781745/3676ef28-2f11-11e5-9b71-f1888f94625c.png)

**Comment by s-a** [comment]
@naholyr this is how it looks now.

It scans the script directory for a DEBUG.md in favor of README.md. This works even if no script was given. This could be useful do write markdown text with preview.

![image](https://cloud.githubusercontent.com/assets/1270662/8786178/ea76956c-2f2c-11e5-94c7-3ddcc07a7c6b.png)

![image](https://cloud.githubusercontent.com/assets/1270662/8786232/22a56742-2f2d-11e5-8a4f-10dab92e6695.png)

I think it is an improvement.

What do you think?

**Comment by s-a** [comment]
For the debugging pro tips i linked to https://developer.chrome.com/devtools/docs/javascript-debugging at the Help/Documentation menu

**Comment by naholyr** [comment]
It's awesome :D I'm almost disappointed I didn't even have time to
contribute it myself ;)
Well done!

**Comment by s-a** [comment]
:+1: I will publish this tomorrow.

**Comment by thabti** [comment]
can we just remove it?

**Comment by s-a** [comment]
Yes
https://github.com/s-a/iron-node/blob/master/.iron-node.js#L11-L12

**Comment by thabti** [comment]
@s-a perfect, thank you.
