### ISSUE TITLE
Weird double filesystem, one sourcemapped, the other not

### ISSUE THREAD

**Issue by krainboltgreene** [s-a/iron-node#80]
![screen shot 2016-01-21 at 1 22 16 pm](https://cloud.githubusercontent.com/assets/334809/12495005/13778b0a-c042-11e5-9089-6397f90f22fd.png)

The lower filesystem is post-transpiled, the upper is (I'm assuming) viewed via the sourcemap and this pre-transpile.

**Comment by s-a** [comment]
`file://` bundels all files requiered by ironNode. For example the ironNode core source code is visible there too in its raw original file system state.  What do you mean with weird?  :ghost: :smile:
