### ISSUE TITLE
Handling links in debugged project README

### ISSUE THREAD

**Issue by mik01aj** [s-a/iron-node#81]
Currently when I click any link in my project's README I see that the webpage is open within the iron-node window. Does this mean that the webpage's JS has access to all the Node's APIs?

**Comment by s-a** [comment]
Yes it is called the electron' s renderer process. 
Here is an example where I open an external browser. https://github.com/s-a/iron-node/blob/master/app/menu.js#L105. I ve seen your engagement at  devtool  repo but did not found time to write there cause I have a realy bad cold :mask:

**Comment by mik01aj** [comment]
Hope you get better soon!

My concern with this issue was that this means opening an arbitrary webpage without the isolation that a web browser has. In other words, it means that the webpage I open can do (almost) anything with my computer without even asking for my permission. This is very, very risky.

Imho if you're parsing the README's markdown source you could as well convert each link to a button that calls `shell.openExternal(...);`. (Or, even better, completely remove that view, just like `devtool` does.)

**Comment by s-a** [comment]
Yes this is all true. I will focus on this for next release. 
Hiding the webview is already possible. 

https://github.com/s-a/iron-node/blob/master/.iron-node.js#L11

In fact many people using it to inject testsuite results or making different things there.

**Comment by mik01aj** [comment]
Btw: https://github.com/atom/electron/issues/1753 - they say there is a `WebView` tag. Maybe you will find it useful.
