### ISSUE TITLE
Source Maps & Error Handling

### ISSUE THREAD

**Issue by mattdesl** [s-a/iron-node#82]
Just thought I'd share my findings from `devtool` since your project might also benefit.

You can get rid of the Node closure and improve syntax errors by overriding some internal Node/Electron features. This is not 100% safe since it may change in future versions of Node/Electron, but it is working well for my purposes.

https://github.com/Jam3/devtool/blob/master/lib/require-hook.js

The above file does some things:
- Uses `syntax-error` to improve error handling
- Uses `combine-source-map` to add source maps to required files
- Sets `require.main` so that it works like you expect in Node
- Optionally, can resolve with the [browser field](https://github.com/defunctzombie/package-browser-field-spec) to make it behave like Webpack/browserify/etc

If you want, I can split some of this out into a separate module that both our projects can build on. Let me know what features (if any) you might be interested in sharing. :smile:

**Comment by mattdesl** [comment]
Syntax errors in iron-node:
<img width="546" alt="screen shot 2016-01-22 at 10 09 34 am" src="https://cloud.githubusercontent.com/assets/1383811/12514237/48f4ac82-c0f0-11e5-82a0-ca40a7824874.png">

In devtool:
<img width="855" alt="screen shot 2016-01-22 at 10 04 20 am" src="https://cloud.githubusercontent.com/assets/1383811/12514220/33faa372-c0f0-11e5-9ac1-5557f899bcb9.png">

**Comment by s-a** [comment]
Thanks for sharing this. 
Syntax errors:  I never had problems with that but I agree your solution looks more userfriendly.  
Source maps : I never used them before... Realy not enough experience with that topic. 
Require Main: I already wrote a testdriven module at https://github.com/s-a/fake-require-main.

Sorry for short response. I have a very bad cold this days.

**Comment by s-a** [comment]
Why are sourcemaps important for you? IronNode was designed to debug side code. Seems you use your debugger f or client code too? 
By the way chrome DevTools supports maps out of the box https://developer.chrome.com/devtools/docs/javascript-debugging#source-maps so ironNode supports this too.

**Comment by mattdesl** [comment]
I use them for two reasons in `devtool` –
1. To hide the ugly Module wrapper that requiring files gives you in Electron
2. To show the in-memory scripts in the Sources panel

So the user can navigate through folders and find a source file in the left panel, and double-click it to set breakpoints that will get hit on reload.

In iron-node, the folders/files in the sources panel are from the workspace, and not in-memory from the `require()` statements, so putting break points in those files will have no effect.

Result is a pretty nice user experience:

<img width="968" alt="screen shot 2016-01-22 at 3 58 44 pm" src="https://cloud.githubusercontent.com/assets/1383811/12522945/ba0993de-c121-11e5-9902-b9c3bfb87221.png">
