### ISSUE TITLE
iron-node is doing something weird with native functions

### ISSUE THREAD

**Issue by jamestalmage** [s-a/iron-node#85]
Reproduction [here](https://github.com/jamestalmage/__iron-node-issue):

```
git clone git@github.com:jamestalmage/__iron-node-issue.git
cd __iron-node-issue
npm install
npm test
```

Reference: https://github.com/sindresorhus/ava/pull/475#discussion-diff-50850112R22

**Comment by s-a** [comment]
@jamestalmage thanks for the detailed repro repo. You are doing heavy professional stuff with that thing :smile:   

On my system ironNode (2.1.13) alerts   

![image](https://cloud.githubusercontent.com/assets/1270662/12669573/e20ee286-c661-11e5-8557-2b70c5e96af6.png)

which I guess depends on chrome and sounds to make sense. It could be a result of calling native methods in different context. So I tried...

[`.setTimeout.bind(window)`](https://github.com/jamestalmage/__iron-node-issue/pull/1)   and [`module.exports.setTimeout = setTimeout.bind(window);`](https://github.com/jamestalmage/__iron-node-issue/pull/2)

Please check out the Pull Request. Both of them make your profiling work :+1:  
If you can confirm that behaviour Id like to change the title to "iron-node is doing something weird with native functions"

**Comment by jamestalmage** [comment]
I don't think it's `iron-node`, apparently it's just Chrome being weird. (even when iron-node is not involved)

**Comment by s-a** [comment]
https://bugs.chromium.org/p/v8/issues/detail?id=4718
