### ISSUE TITLE
Cannot debug mocha/jsdom tests with iron-node

### ISSUE THREAD

**Issue by loiclacombe** [s-a/iron-node#90]
Hi,
If I try to debug jsdom/mocha tests, I get this in the iron-node debug console:

> TypeError: Cannot assign to read only property 'document' of [object global]

which does totally makes sense as my usage of jsdom is the following
`global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
global.window = document.defaultView;
global.navigator = {userAgent: 'node.js'};`

FYI, jsdom creates a virtual dom thus allowing me to test my react components without the painful and obscure _jest_.

So, is there a way to use iron-node to debug my react components/mocha/jsdom unit tests?

**Comment by s-a** [comment]
I am not familiar with react but if you do that to mock the DOM for nodejs this is not necessary in ironNode. Electron is a hybrid environment. Could you try to skip the mocking because document already exist in ironNode environment?

``` javascript
// tests/testdom.js
module.exports = function(markup) {
  if (typeof document !== 'undefined') return;
  var jsdom = require('jsdom').jsdom;
  global.document = jsdom(markup || '');
  global.window = document.parentWindow;
  global.navigator = {
    userAgent: 'node.js'
  };
};
```

**Comment by loiclacombe** [comment]
You're totally right, the following piece of code did the job:

```
var jsdom = require('jsdom');

if (typeof document === 'undefined'){
  var jsdom = require('jsdom').jsdom;
  global.document = jsdom(markup || '');
  global.window = document.parentWindow;
  global.navigator = {
    userAgent: 'node.js'
  }; 
}
```

I did not use the usual suggested stuff,a properly imported testdom.js module in each test file, because jsdom need to be always loaded before the other modules and babel sometimes inserts other requires before.

Thanks a lot!
