### ISSUE TITLE
Some packages break because of global window variable

### ISSUE THREAD

**Issue by hendrikswan** [s-a/iron-node#91]
Looove iron-node! 

Unfortunately on the project where I need it the most, I can't use it. I'm using the aws-sdk package, and it checks whether it runs in the browser by the presence of the window variable.

``` javascript

  readFileSync: function readFileSync(path) {
    if (typeof window !== 'undefined') return null;
    return util.nodeRequire('fs').readFileSync(path, 'utf-8');
  },

```

Do you have any advice for me and people who are experiencing similar issues?

**Comment by s-a** [comment]
Thanks. This was already reported at #71 I will reopen #71 to continue there.
