### ISSUE TITLE
View `node_modules` directory in inspector window

### ISSUE THREAD

**Issue by dtothefp** [s-a/iron-node#92]
In `node-inspector` I seem to have access to the entire file system of my application and am free to place break points in my `node_modules` directory. I'm running `iron-node` with compiled es6 by babel in the case of the first two screenshots below, and am running `iron-node` on a `gulp` build using the `babel-register` in the case of the last screenshot. I've seen other issues on this repo where users show they can see the `node_modules` directory in their inspector so I'm unsure of what I'm doing wrong?
##### Node Inspector

<img width="854" alt="screen shot 2016-02-07 at 10 09 37 am" src="https://cloud.githubusercontent.com/assets/4656726/12873134/dc1c54de-cd83-11e5-94fd-62f53e8549d6.png">

It seems in `iron-node` that I have to manually place a `debugger` in my `node_modules` and even then I wouldn't be able to place breakpoints in the inspector in subsequent `node_modules`
##### Iron Node

<img width="675" alt="screen shot 2016-02-07 at 10 12 51 am" src="https://cloud.githubusercontent.com/assets/4656726/12873131/cfa9114c-cd83-11e5-9bca-93078f6ea9a5.png">
##### Gulp task

<img width="789" alt="screen shot 2016-02-07 at 10 29 47 am" src="https://cloud.githubusercontent.com/assets/4656726/12873224/c4496d0e-cd85-11e5-9ccd-5643467268c4.png">

**Comment by s-a** [comment]
You should be able to find each module loaded when you press `Ctrl+p`. Be shure you select the version wrapped by the Node.js module wrapper.

Here is a more detailed descrption.
https://github.com/s-a/iron-node/blob/master/docs/MASTER-THE-BREAKPOINTS.md

**Comment by s-a** [comment]
May be people using this feature?

**Comment by s-a** [comment]
https://github.com/s-a/iron-node/blob/fd921c39b8a44379749acacbaeb8dc987ec08ec6/.iron-node.js#L14
