### ISSUE TITLE
`global` should be node's `global`.

### ISSUE THREAD

**Issue by johnjbarton** [s-a/iron-node#94]
After the fix to issue #71 we have the ability to set some global variables to `undefined`. That helps because `window` can be set to `undefined` to match the nodejs environment.

However this is not sufficient. We also need the globals that nodejs provides to be provided. For example, we need `global` to be as documented:
https://nodejs.org/api/globals.html
not `undefined` (as the new `.iron-node.js` config supports) nor `window` as it appears to arrive by default.

Progress on #71 makes me very hopeful that the correct nodejs environment can be provided. Of course electron has the correct nodejs `global` property when it boots, but it looks like it sets `global` to `window` to support the UI.  (Again a short paragraph on iron-node architecture would be very helpful).

**Comment by johnjbarton** [comment]
Maybe a preload script can solve this:
http://electron.atom.io/docs/all/

```
preload String - Specifies a script that will be loaded before other scripts run in the page. 
This script will always have access to node APIs no matter whether node integration is 
turned on or off. The value should be the absolute file path to the script. When node 
integration is turned off, the preload script can reintroduce Node global symbols back 
to the global scope. See example here.
```

**Comment by johnjbarton** [comment]
Upon further investigation, it does not seem like it will be possible to solve this issue.

The solution to issue #71 works for node modules because the parameters defined on the wrapper function become local references in the module.  So we can defined `global` to be something very close to the nodejs global simply:

```
global={exports:exports, require:require, module:module, process:process};
```

But any code that is compiled against the environmental global object will still see `Window`.  This means that operations on the real global object will not be reflected on the local reference `global` used inside of the module.

I also tried deleting the property `global.window` in hopes that I could keep the default `Window` global object but make it more node-like. Unfortunately `Window.window` (and `Window.document`) seem to be special properties that JavaScript cannot delete.

I guess this only affects low-level node code. I'll see if I can re-work our code to avoid using the global object.

I still think it may be worthwhile to define the `global` reference in the wrapper to be closer to nodejs's global.

**Comment by s-a** [comment]
Sorry for delay and thanks for your time to explore this. 
Have you tried your value assignment of a `global` at 
https://github.com/s-a/iron-node/blob/5195b8b1c3a7649eaba4519604ff8c461bd3f145/app/require-custom-wrap.js#L19 ? You could try to inject your code into string of first function wrapper. Maybe this works.

**Comment by s-a** [comment]
The attempt seems to work . 

I placed your code into local .iron-node.js

``` javascript
  "nodeModule" : {
    "scriptInjection" : "global={exports:exports, require:require, module:module, process:process};\ndebugger;",  // Prepend some custom javascript code to your code.
    "arguments" : [                   // Add additional arguments. Node will pass undefined to these parms. This is usefull to mimic a native browser environment.
      "window", "document", "self", "global", "navigator", 
    ]  
  },
```

![image](https://cloud.githubusercontent.com/assets/1270662/14059095/76ff838a-f337-11e5-8963-73c10d078201.png)
