### ISSUE TITLE
How to run dev version?

### ISSUE THREAD

**Issue by johnjbarton** [s-a/iron-node#95]
https://github.com/s-a/iron-node/blob/master/CONTRIBUTING.md

Has a cryptic line: 

```
cd sulu
```

What is that about?  

Also it would be helpful if the page explained how to run the dev version.

**Comment by s-a** [comment]
This should be `iron-node` there are some sample scripts to run iron-node in dev-mode in `package.json`.

**Comment by s-a** [comment]
https://github.com/s-a/iron-node/blob/master/CONTRIBUTING.md#execute-iron-node-in-development-mode
