### ISSUE TITLE
Can't resolve path on some modules when using loopback.io framework

### ISSUE THREAD

**Issue by raabbajam** [s-a/iron-node#96]
I have never use this or other node debugger, so please excuse me beforehand if I missed something.

I want to run my [loopback](http://loopback.io/) app with iron-node (i.e `iron-node server/server.js`), but it throws error stating `Error: Cannot resolve path "loopback/server/middleware/urlNotFound"`.

From the message I figure this is caused by missing module and the path is not resolved. But when I run using `node server/server.js` it works as usual without error. 

I wonder if there is some configurations to set, like app root directory that has to verbosely set or something. If so please kindly point me to the right direction (documentation).

I also use [nvm](https://github.com/creationix/nvm) as my node executable (don't know if it has anything to do with it).

Additional information:

```
❯ node -v
v4.2.2

❯ which node
/home/raabbajam/.nvm/versions/node/v4.2.2/bin/node

❯ npm ls iron-node -g
/home/raabbajam/.nvm/versions/node/v4.2.2/lib
└── iron-node@2.2.15

❯ lsb_release -a  
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:    14.04
Codename:   trusty

❯ uname -a  
Linux kat 3.19.0-51-generic #58~14.04.1-Ubuntu SMP Fri Feb 26 22:02:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Thank you.

**Comment by s-a** [comment]
I like to take a closer look at this. Can you create a reproducable sample that i can clone from github and install with npm install?

**Comment by raabbajam** [comment]
Hi @s-a, [this](https://github.com/raabbajam/loopback-sandbox) is a fork of loopback-sandbox, more or less a clean out-of-the-box loopback typical apps.
You just have to clone it and npm install then `iron-node server/server` (the main script).
The error appeared too, just like how it does in my own project.

Here is an additional error message from the iron-node console tabs:

```
 Error: Cannot resolve path "loopback/server/middleware/urlNotFound"

  - compiler.js:356 resolveAppPath
    [loopback-sandbox]/[loopback-boot]/lib/compiler.js:356:15

  - compiler.js:681 resolveAppScriptPath
    [loopback-sandbox]/[loopback-boot]/lib/compiler.js:681:22

  - compiler.js:587 resolveMiddlewarePath
    [loopback-sandbox]/[loopback-boot]/lib/compiler.js:587:29

  - compiler.js:475 
    [loopback-sandbox]/[loopback-boot]/lib/compiler.js:475:24

  - Array.forEach

  - compiler.js:474 
    [loopback-sandbox]/[loopback-boot]/lib/compiler.js:474:18

  - Array.forEach

  - compiler.js:469 
    [loopback-sandbox]/[loopback-boot]/lib/compiler.js:469:30

  - Array.forEach

  - compiler.js:467 buildMiddlewareInstructions
    [loopback-sandbox]/[loopback-boot]/lib/compiler.js:467:15
```

Thanks. :tea:

**Comment by s-a** [comment]
Hmm i think these folders are not resolved correct. Do they need to exist on the harddrive?

![image](https://cloud.githubusercontent.com/assets/1270662/13529189/0cecd8d0-e21b-11e5-977f-c0dd3e406c44.png)

Can you open an issue at loopback and ask if they are willing to suport the Electron environment?

**Comment by s-a** [comment]
atom.asar is a file an not a folder

**Comment by s-a** [comment]
Could this be related to #98 nodes environment variables. As @pragyandas reported at #99 this works in visual studio code out of the box.

**Comment by s-a** [comment]
I will close this issue refering to https://github.com/strongloop/loopback/issues/2169
