### ISSUE TITLE
Unable to run express server with webpack + hot reloading

### ISSUE THREAD

**Issue by tnrich** [s-a/iron-node#97]
I'm running into multiple issues, but the first one looks like this:

```
  TypeError: setInterval(...).unref is not a function

  - middleware.js:58 createEventStream
    [EST]/[webpack-hot-middleware]/middleware.js:58:17

  - middleware.js:12 webpackHotMiddleware
    [EST]/[webpack-hot-middleware]/middleware.js:12:21

  - server.js:106 startServer
    /Users/tnrich/Sites/EST/server.js:106:46

  - connectToDB.js:28 startDB
    /Users/tnrich/Sites/EST/server/connectToDB.js:28:2

  - server.js:90 Object.<anonymous>
    /Users/tnrich/Sites/EST/server.js:90:1

  - app.js:245 boot
    [lib]/[iron-node]/app/app.js:245:3

  - app.js:252 
    [lib]/[iron-node]/app/app.js:252:1
```

![image](https://cloud.githubusercontent.com/assets/2730609/13479583/e07df606-e08c-11e5-9242-3d55fb98f388.png)

I'm not quite sure what to do. If you have any ideas I'd love to hear em. Thanks!
Thomas

**Comment by s-a** [comment]
Seems like timers in Node differ from timers in browser. Maybe there exist some shims ?

**Comment by s-a** [comment]
Could you pls add an issue at webpack? maybe they are willing to support the electron environment.

**Comment by s-a** [comment]
@tnrich can you take a look at https://github.com/webpack/webpack/issues/2235 pls?

**Comment by tnrich** [comment]
Hey @s-a , sorry for the delay. I've taken a look at the issue. Is there something you'd like me to do in particular? Did you see sokra's suggestion to try `target: "electron"` ?

**Comment by s-a** [comment]
I have not used Webpack yet. I think he means that there is an option at webpack configs? They added an enhancement badge at the issue.  It might be the best if you ask there if you can do something in your project to resolve the issue.

**Comment by s-a** [comment]
I will close this for https://github.com/webpack/webpack/issues/2235 Unless we have more infos about how we can work around this in iron-node source code.
