### ISSUE TITLE
NODE_PATH environment variable is ignored

### ISSUE THREAD

**Issue by ericelliott** [s-a/iron-node#98]
## Reproduce

The `NODE_PATH` environment variable is set correctly, but it seems to be ignored when I do this:

``` sh
    "debug:unit": "NODE_PATH=source iron-node source/test/unit/debug.js",
```

This works fine:

``` sh
    "test:unit": "NODE_PATH=source babel-node source/test/unit/index.js",
```

`debug.js` looks like this:

``` js
require('babel-core/register');
require('./index.js');
```

As you can see, the test directory containing `debug.js` is inside the `source` directory.

**Comment by gmcquistin** [comment]
Did you manage to fix this issue?

**Comment by ericelliott** [comment]
No.

**Comment by s-a** [comment]
Just an idea for a quick work around. Is it possible to set `NODE_PATH` from JavaScript? We are able to inject code with https://github.com/s-a/iron-node/blob/d10776fd381d061cd27f7330368a0fb62f6e507b/.iron-node.js#L4

**Comment by ericelliott** [comment]
I have no idea. What would that code look like?

**Comment by s-a** [comment]
Justa guess, but `process.env.NODE_PATH = foo` may work?

**Comment by ericelliott** [comment]
What is `foo`? Where does the value come from?

**Comment by s-a** [comment]
Foo should be your path you want to set
Am 24.03.2016 22:58 schrieb "Eric Elliott" notifications@github.com:

**Comment by ericelliott** [comment]
What if my application requires 60 environment variables for configuration? Are you suggesting that I hardcode all of them just so iron-node will work as expected?

**Comment by s-a** [comment]
Just a test / workaround. So far I do not know how to pass env vars to electron environment. This 60 vars are coded in some bash or npm package script? If it works we need to decide how to map your env vars and assign them automaticly at debug session start. From what I think now we need to hardcode them anywhere if electron can not see environment var s. :\  
These settings depends on the current workstation right?  Maybe we should introduce a new local configuration file.

**Comment by s-a** [comment]
If it works we could catch env here https://github.com/s-a/iron-node/blob/d10776fd381d061cd27f7330368a0fb62f6e507b/bin/run.js#L33 and pass them to electron instance. But the content is huge how to decide which of them are relevant?

**Comment by ericelliott** [comment]
> how to decide which of them are relevant?

I wouldn't try to filter it.

**Comment by s-a** [comment]
@ericelliott  Have you figured out if it works for you? I would start an implementation then.

**Comment by hoschi** [comment]
I added the file `source/test/debug.js` with content:

```
require('babel-core/register');
require('./index.js');
//process.env.NODE_PATH = 'source'
process.env.NODE_PATH = '../'
```

to the repo (from @ericelliott ) https://github.com/ericelliott/react-pure-component-starter
but both options for `NODE_PATH` didn't work. I tried to check if it was even recognized, but `process.env` gives me nothing in the spawned iron-node console.

**Comment by s-a** [comment]
@hoschi ty for figuring this out. Just opened an issue at the electron repo. I hope they can help out.

**Comment by jackgeek** [comment]
Is there a workaround for this?  I can't use iron-node at all due to this problem because my mocha tests can't resolve modules on the NODE_PATH

**Comment by s-a** [comment]
Not yet . Hoschi' s efforts did not work. One last idea I have : We could try to set `ENV`in electron main process. https://github.com/s-a/iron-node/blob/master/app/index.js can someone try this out? Maybe we can change the content there.

**Comment by s-a** [comment]
This is by electron design and for security. We need to add path to `module.paths`. This can be done as described here https://github.com/s-a/iron-node/issues/98#issuecomment-201025047. @all: does this solve your issue?

**Comment by jackgeek** [comment]
I tried setting process.env.NODE_PATH in .iron-node.js but this did not work.  Perhaps my issue has a different cause?

http://stackoverflow.com/questions/37181535/module-js-cannot-find-modules-when-running-iron-node

**Comment by jackgeek** [comment]
This SO answer suggests setting process.env.NODE_PATH once the app has started won't work because the module paths are cached: [Determine project root from a running node.js application](http://stackoverflow.com/questions/10265798/determine-project-root-from-a-running-node-js-application#18721515)

I am at a loss as to how to set this before iron-node starts, it is always undefined

**Comment by s-a** [comment]
@jackgeek The creators of electron [suggested](https://github.com/electron/electron/issues/5483) to add your path to `module.paths`. You can try to add your code to a local `.iron-node.js` file and place code to add  items to `module.paths` in  `scriptInjection` in a local [.iron-node.js](https://github.com/s-a/iron-node/blob/d10776fd381d061cd27f7330368a0fb62f6e507b/.iron-node.js#L4).

I think `module.paths` is an array where you can push a hard coded string.

Hope this helps.

**Comment by jackgeek** [comment]
This worked!  thank you so much!!! :smiley:

**Comment by s-a** [comment]
Thank you for testing this out. I am happy we have a solution for this :+1:

**Comment by jackgeek** [comment]
For anyone else with this problem.  Here is the .iron-node.js config file that worked for me:

```
process.env.NODE_PATH = process.cwd(); // fix problem where modules are not resolved - Jack Allan.
var path = require("path");
var settings = {
  "nodeModule" : {
     "scriptInjection" : "module.paths.push(process.env.NODE_PATH);",  // fix problem where modules are not resolved - Jack Allan.
  },
  "v8": {
    "flags" : [                             // DEFAULT=[]; https://github.com/thlorenz/v8-flags/blob/master/flags-0.11.md
    ]
  },
  "app": {
    "native+"               : false,   // DEFAULT=FALSE; extends require to search native modules respecting the current v8 engine version.
    "autoAddWorkSpace"      : false,  // DEFAULT=TRUE; disables the autoAddWorkSpace behavior.
    "openDevToolsDetached"  : false,  // DEFAULT=FALSE; opens the dev tools windows detached in an own window.
    "hideMainWindow"        : false,  // DEFAULT=FALSE;  hides the main window to show dev tools only.
  },
  "workSpaceDirectory"        : function(argv) {  // determines the workspace directory for specific commandline applications.
    var result = "";
    if (argv[2]){
      result = path.dirname(argv[2]);
      var startupScriptName = path.basename(argv[2]).toLowerCase();

      switch(startupScriptName) {
          case "_mocha":
            result = process.cwd();
            break;
          default:
            result = path.resolve(result);
            break;
      }
    }

    return result;
  }
};

module.exports = settings;

```

**Comment by ericelliott** [comment]
What about other environment variables? e.g., configuration settings such as API tokens, etc...?

This isn't so much a solution as an ugly, hacky workaround. =)

**Comment by s-a** [comment]
I plan to implement an automatism right here https://github.com/s-a/iron-node/blob/ddf3bde0250c4e11c35d040724d17e02f9fe7ae5/app/app.js#L252. We could need some feedback for the electron 1.0.2 migration on non windows systems https://github.com/s-a/iron-node/releases/tag/v3.0.1 to ensure this release is stable cross platorm.
